### ISSUE TITLE
azure: Environment should include the ACR endpoint suffix

### ISSUE THREAD

**Issue by colemickens** [Azure/go-autorest#102]
https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L21

Please add the ACR suffix to this struct and then for each environment that is defined.

**Comment by mcardosos** [comment]
Hey @colemickens
Do you happen to know which suffix each cloud uses? I couldn't find lots of info about it. Or all clouds use `azurecr.io`?

**Comment by colemickens** [comment]
Cc @sajayantony
