### ISSUE TITLE
Get Azure Active Directory Authentication Library (ADAL) for Go

### ISSUE THREAD

**Issue by mcardosos** [Azure/go-autorest#103]
I believe some code that lives in this repo should live inside an ADAL repo. There is ADAL for other languages, including [Java](https://github.com/AzureAD/azure-activedirectory-library-for-java), [Node](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs), [Ruby](https://github.com/AzureAD/azure-activedirectory-library-for-ruby), etc.
@cosmincojocar I know you have used Go before, and also have worked on ADAL for other languages. What do you think?
cc @jhendrixMSFT @marstr @salameer

**Comment by colemickens** [comment]
Yes, yes, yes, please. I'm actively doing some work in `token.go`. It needs some love and a refactoring due to some mistakes I made in the initial design

I'd love to see it become a full, separate ADAL library. CC: @jkapil

**Comment by cosmincojocar** [comment]
I'd decently like to see this in a stand ADAL library.  It will be really helpful for a microservices application written in Go which relies on AAD as IdP but does not use the Azure SDK. Such an application most likely needs service to service authentication and token verification.

**Comment by salameer** [comment]
@eduardkoller  would this be on yourside right now :)?

If so can you point to where this code lives at the moment

**Comment by colemickens** [comment]
(Please note, I have a branch where I'm adding MSI support to go-autorest and I had added cert auth, so I'd like to be involved in conversations about splitting the `azure` dir in here out into an ADAL-Go library. Thanks.)

**Comment by salameer** [comment]
@eduardkoller small ping :)

**Comment by mcardosos** [comment]
@DavidObando
I think your team could be interested in ADAL for Go too.

**Comment by salameer** [comment]
Closing this issue as it doesn't belong in this repo.

@eduardkoller we understand that this is not budgeted on your side at the moment but it would probably be a good idea to at-least open a feature request in the right place to be tracked in case it gets picked up in the future.
