### ISSUE TITLE
JSON unmarshaling does not cope with byte-order mark

### ISSUE THREAD

**Issue by rogpeppe** [Azure/go-autorest#109]
I sometimes see an error like this:

    error response cannot be parsed: "\ufeff{\"odata.error\":{\"code\":\"Request_MultipleObjectsWithSameKeyValue\",\"message\":{\"lang\":\"en\",\"value\":\"Another object with the same value for property servicePrincipalNames already exists.\"},\"requestId\":\"46a97035-e286-4d41-8eee-ae33de2f0288\",\"date\":\"2017-01-18T12:31:21\"}}" error: invalid character 'ï' looking for beginning of value

It looks like the error response from Azure sometimes contains a byte-order mark that Go's JSON decoder does not like. It should probably be trimmed before parsing.

**Comment by salameer** [comment]
@mcardosos:

- Can you investigate with the service team on the reasoning for the adding this byte-order. you can work with @kirthik to nail down the service team contacts.
- Can you also check if this this is the only byte order value that they would be sending before omitting it.

**Comment by salameer** [comment]
@rogpeppe 

Thanks for contacting us can you please provide a sample API that's showing this behavior.

"Sample of your code would be even better :)"

**Comment by garimakhulbe** [comment]
Error is coming as `odata.error` which might be failing in json unmarshal.
```Go
ServiceError *ServiceError `json:"error"`
```

**Comment by axw** [comment]
FWIW, the code in question is in:
 - https://github.com/juju/juju/blob/staging/provider/azure/internal/ad/client.go
 - https://github.com/juju/juju/blob/staging/provider/azure/internal/ad/serviceprincipals.go
 - https://github.com/juju/juju/blob/staging/provider/azure/internal/azureauth/interactive.go#L208
