### ISSUE TITLE
v7.2.3 version.go still reports v7.2.2

### ISSUE THREAD

**Issue by marstr** [Azure/go-autorest#110]
The commit tagged v7.2.3 will still report as v7.2.2 using  the `autorest.Version()` function.

**Comment by marstr** [comment]
CI testing should be updated to prevent this happening again.

**Comment by marstr** [comment]
Because we'd like to treat tags as immutable, there isn't really anything we can do to fix this for v7.2.3. However, we can test to make sure this doesn't happen again in the future. The PR above (#111) takes care of that. Once that PR is merged, I'll close this issue.

**Comment by mcardosos** [comment]
BTW, I can tag v7.2.4 once we merge the PR
