### ISSUE TITLE
error format seems to have changed

### ISSUE THREAD

**Issue by rogpeppe** [Azure/go-autorest#142]
When I make a request to the Azure API that returns an error,
I see a response like this:

    {"odata.error":{"code":"Request_ResourceNotFound","message":{"lang":"en","value":"Resource not found for the segment 'me'."}}}

This ends up producing an error like:

    graphrbac.ObjectsClient#GetCurrentUser: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error"

because azure.ServiceError does not define the correct response type.

**Comment by marstr** [comment]
Thanks for reporting this, @rogpeppe! I'll start investigating now!

**Comment by marstr** [comment]
@rogpeppe, do you only experience this issue when targeting RBAC, or is this a consistent issue across all services?

**Comment by rogpeppe** [comment]
Thanks for the swift response. That's the API I was investigating - I haven't tried any others yet.

For the record, this was the code I was running:

	package main
	
	import (
		"bytes"
		"io"
		"io/ioutil"
		"log"
		"net/http"
	
		"github.com/Azure/azure-sdk-for-go/arm/graphrbac"
		"github.com/Azure/go-autorest/autorest"
		"github.com/Azure/go-autorest/autorest/adal"
		"github.com/Azure/go-autorest/autorest/azure"
		"github.com/kr/pretty"
	)
	
	func main() {
		clientId := "xxx"
		clientSecret := "xxxx"
		tenantId := "xxx"
	
		oauthConfig, err := adal.NewOAuthConfig(azure.PublicCloud.ActiveDirectoryEndpoint, tenantId)
		if err != nil {
			log.Fatalf("NewOAuthConfig: %v", err)
		}
		token, err := adal.NewServicePrincipalToken(*oauthConfig, clientId, clientSecret, azure.PublicCloud.ActiveDirectoryEndpoint)
		if err != nil {
			log.Fatalf("NewServicePrincipalToken: %v", err)
		}
	
		client := graphrbac.NewObjectsClient(tenantId)
		client.Authorizer = autorest.NewBearerAuthorizer(token)
		client.Sender = logger{}
	
		info, err := client.GetCurrentUser()
		if err != nil {
			log.Fatalf("cannot get current user: %v", err)
		}
		pretty.Println(info)
	}
	
	type logger struct{}
	
	func (logger) Do(req *http.Request) (*http.Response, error) {
		log.Printf("do %v", req.URL)
		log.Printf("    %q", req.Header)
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			log.Printf("-> error %v", err)
		} else {
			log.Printf("-> code %v", resp.Status)
			var buf bytes.Buffer
			io.Copy(&buf, resp.Body)
			log.Printf("    body %q", buf.Bytes())
			resp.Body = ioutil.NopCloser(&buf)
		}
		return resp, err
	}

Tangentiallly, do you by any chance know of any way of obtaining a service principal that will allow an app to find out the user name or id that created it? (that's what I was attempting to do at the time)

**Comment by marstr** [comment]
Howdy @rogpeppe, sorry for the delay! I ended up out sick yesterday.

In terms of your code snippet above, try creating the Service Principal Token and requesting access to the GraphEndpoint like this:

``` Go
token, err := adal.NewServicePrincipalToken(*oauthConfig, clientId, clientSecret, azure.PublicCloud.GraphEndpoint)
```

If that doesn't work, try swapping out for the ResourceManagment endpoint. Let me know if neither of those things work!

**Comment by marstr** [comment]
Oh, one more thing, depending on the way the token was created, at times one may need to `Refresh()` it. Make sure to try that too in order to ensure the SPT has been properly initialized.

**Comment by tombuildsstuff** [comment]
@marstr I have a feeling that there's an issue tracking this elsewhere - but we're seeing this across all services, here's some examples:

```
network.RouteTablesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Put https://management.azure.com/subscriptions/*******/resourceGroups/acctestRG-661191832347465209/providers/Microsoft.Network/routeTables/acctestrt661191832347465209?api-version=2017-09-01: http: ContentLength=99 with Body length 0
```

This one ^ I've been struggling to reproduce locally, however we see it fairly consistently in CI

```
network.SubnetsClient#Delete: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="InternalServerError" Message="An error occurred."
```

```
Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error"
```

For these two error messages the actual error message is visible in the HTTP response (when routing the traffic through a tool like Charles Proxy/Fiddler) - however it's not being exposed correctly

Would it be possible to look into exposing these error messages?

Thanks!

**Comment by jhendrixMSFT** [comment]
There has been some work on error reporting and I suspect this has been fixed, working on the repro to confirm.

**Comment by jhendrixMSFT** [comment]
For the second example (the "Unknown service error") I'm pretty sure this is the same issue that will be fixed in PR https://github.com/Azure/go-autorest/pull/228.

**Comment by jhendrixMSFT** [comment]
OK for the first example (the "InternalServerError") this might be a deficiency in the LRO implementation; it grabs the status code and message but nothing else.  @tombuildsstuff I don't suppose you have a response body handy that demonstrates the missing information?

**Comment by jhendrixMSFT** [comment]
I'm going to close this as there are separate issues for each item reported here.
