### ISSUE TITLE
Add a retry mechanism for authentication

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/go-autorest#144]
Investigate adding a mechanism for automatically refreshing oath tokens.

**Comment by mcardosos** [comment]
Oauth tokens are refreshed [just before every request](https://github.com/Azure/go-autorest/blob/master/autorest/client.go#L178). `WithAuthorization()` implementation [includes the refresh](https://github.com/Azure/go-autorest/blob/master/autorest/authorization.go#L43).

**Comment by jhendrixMSFT** [comment]
Does storage use this implementation or just ARM?

**Comment by mcardosos** [comment]
Storage data plane gens a new token with each request. Authorization header is very different in storage.

**Comment by jhendrixMSFT** [comment]
Additional context when I opened this issue.
"Autorest appears to handle failure/retry (just from glancing at code, haven’t taken a close look yet). However, it appears that Outh authentication happens early and the caller has to handle auth failures. It doesn’t retry later on and calls to ZonesClient or RecordSetsClient fail because there’s no valid auth token. Is there a way to configure retrying auth failures at the next call to a client function?"

**Comment by jhendrixMSFT** [comment]
@xtophs Looking at the code, the oauth token is refreshed just before every request (see @mcardosos previous comment).  Can you provide more info (or even some sample code) where you're seeing this happen?

**Comment by jhendrixMSFT** [comment]
Closing as this is not actionable.
