### ISSUE TITLE
Unable to use KeyVaultEndpoint as AAD auth resource endpoint

### ISSUE THREAD

**Issue by karataliu** [Azure/go-autorest#145]
As of https://github.com/Azure/go-autorest/blob/58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d/autorest/azure/environments.go#L46

The KeyVaultEndpoint is `https://vault.azure.net/`

If using that KeyVaultEndpoint as AAD's resource, following https://github.com/Azure/go-autorest/blob/master/autorest/azure/example/main.go#L86

It result in 401 response with following header:
```
Www-Authenticate:[Bearer authorization="https://login.windows.net/xxx", resource="https://vault.azure.net"]
```

If manually specify `https://vault.azure.net` (no tailing slash), the request will succeed.

See also:
https://github.com/Azure/azure-sdk-for-python/blob/5e51e1f4a404f8c1d87227da14a68ca924bc180c/doc/sample_azure-keyvault.rst

Adding the tailing slash makes the endpoints consistent, but then the SDK it's not usable. User has to manually tune those endpoints, and it does not make sense for multi-cloud environments.

Shall we ask the service to accept the ending slash, or change the SDK?

**Comment by mcardosos** [comment]
Hello @karataliu ! @marstr will take a look at this.

**Comment by marstr** [comment]
Howdy @karataliu, sorry this is has gone without attention so long. 

This is getting a lot of attention, and the root cause was taken care of by @jhendrixMSFT in #156. I'll follow up in the next week or so to make sure that any residual items to take advantage of Joel's work get mopped up.

**Comment by marstr** [comment]
Calling this good :) If anybody experiences additional troubles here, feel free to open a new issue.
