### ISSUE TITLE
Convenience func to add many decorators at once

### ISSUE THREAD

**Issue by mcardosos** [Azure/go-autorest#147]
As suggested by @JackQuincy in https://github.com/Azure/azure-sdk-for-go/issues/658

**Comment by JackQuincy** [comment]
Thanks

**Comment by JackQuincy** [comment]
If you want the design I had, I actually have a branch in my fork that has this and a unit test for it. If you want I could start a PR. Let me know

**Comment by mcardosos** [comment]
Awesome! PRs are always welcome :)

**Comment by jhendrixMSFT** [comment]
Closing since the PR stalled.
