### ISSUE TITLE
Add support for OAuth2 authorization flow

### ISSUE THREAD

**Issue by chessman** [Azure/go-autorest#149]
I need to authorize clients with standard OAuth2 authorization flow. It seems that only secret, certificate and device flows are supported now. For example, other SDKs have 
 `AcquireTokenWithAuthorizationCode` method. Any plans to support it?

**Comment by mcardosos** [comment]
Hello @chessman!!

Thanks for reaching out!

We'll be adding this request to our backlog and keep you posted 

Thanks again

**Comment by araoko** [comment]
The Token or ServicePrincipalToken type can be modified to include information on the flow type
The refreshInternal function on ServicePrincipalToken  can be modified to check for this information to determine what to set as the grant_type value

**Comment by halfcrazy** [comment]
Also need UserPassCredentials, like https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_active_directory.py#L321

**Comment by vladbarosan** [comment]
Test comment
