### ISSUE TITLE
Revamp retries

### ISSUE THREAD

**Issue by mcardosos** [Azure/go-autorest#157]
Today, the way go-autorest retries is not flexible enough.
Related issue
https://github.com/Azure/azure-sdk-for-go/issues/714
@yuwaMSFT2

**Comment by majedev** [comment]
A couple of suggestion:

* Add support for `io.ReadSeeker` auto-rewinding during retries. This will avoid copying types like `os.File` to a memory buffer during preparation.
* If copying readers to memory buffer is absolutely necessary, then do it lazily on read (so the reader will be copied during 1st read), not during the preparation step. This will avoid a copy when there's a network error. Might be an overkill.

**Comment by jhendrixMSFT** [comment]
We will not be fixing this in go-autorest, it will be addressed in the v3 autorest.go code generator that uses the pipeline model (https://github.com/Azure/azure-pipeline-go).
