### ISSUE TITLE
Stop vendoring dependencies

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/go-autorest#16]
Per our discussion at https://github.com/Azure/azure-sdk-for-go/issues/262 we should probably stop using Godeps for this library repository. Also I noticed the SDK vendors the same dependencies as here over there. So it's probably redundant.

**Comment by colemickens** [comment]
I have a branch switched over to glide. Was going to discuss it with you and Brendan in the morning.

**Comment by colemickens** [comment]
(I have branches of both go-autorest and azure-sdk-for-go moved over.) I partially picked glide because I use the alias feature regularly.

**Comment by ahmetalpbalkan** [comment]
@colemickens It's for a brownbag on glide...:stuck_out_tongue_closed_eyes:

**Comment by brendandixon** [comment]
@ahmetalpbalkan @colemickens Let's chat. I am very likely all for this.
