### ISSUE TITLE
azure stack support

### ISSUE THREAD

**Issue by andyzhangx** [Azure/go-autorest#161]
Hi,
   Have you ever tried adal on azure stack env? I have been using adal in azure stack env, trying to use service principal connecting to azure stack, while I always got below error:
2017/08/04 07:40:17 Error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://adminmanagement.local.azurestack.external/subscriptions/a3368291-e427-41b0-b790-66b7be21017b/providers/Microsoft.Storage/checkNameAvailability?api-version=2015-06-15: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'

    And then If I comment out below line in adal, it would proceed.
https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L373

**Comment by mcardosos** [comment]
Hello @andyzhangx !
Please submit a PR, PRs are always welcome :)

**Comment by andyzhangx** [comment]
Hi @mcardosos , you mean comment out line 373? This issue only happens on azure stack, it does not happen on global azure, is it reasonable?

**Comment by mcardosos** [comment]
Well, the fix should work on both cases. Maybe there is another possible status code?

**Comment by marstr** [comment]
Closing this out for now, we're still working on our roadmap for supporting Azure Stack.

**Comment by AntoineGa** [comment]
Do you have any info on the roadmap or on a fix ?
