### ISSUE TITLE
Expose authorization response error code for better debugging

### ISSUE THREAD

**Issue by yuwaMSFT2** [Azure/go-autorest#167]
We are doing ARM calls with AAD service principal authorization

This could fail with authentication. Right now the returned error has information like below:
autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/xxxxxxxxx/oauth2/token?api-version=1.0 failed with 400 Bad Request: StatusCode=400

autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/xxxxxxxxx/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401

However there are many reasons that Graph API can give you 400. Is it possible to expose the additional error code from the response?

**Comment by yuwaMSFT2** [comment]
@SajayAntony @sivagms

**Comment by marstr** [comment]
Howdy Folks, this is something that drives me crazy too. I believe that #170 should address this. If not, I'll try to add something in. It's been on my mental backlog for a long time.

**Comment by jhendrixMSFT** [comment]
This should be fixed in go-autorest v9.5.0.  Please re-open if you still experience this issue with v9.5.0.
