### ISSUE TITLE
Recent Refactoring to Long Running Operations

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/go-autorest#193]
👋 

I've seen [this recent PR](https://github.com/Azure/autorest.go/pull/39) which changes the way that Long Running Operations are handled, such that it effectively removes the polling support from the SDK and instead pushed that onto consumers of the SDK.

Within Terraform, we rely pretty heavily on the automatic polling available within the Go SDK - as such I'm concerned that removing these methods will lead to a considerable increase in code (and thus complexity) for us - when currently this is one of the major benefits of using the Go SDK over when we used to use the Riviera SDK.

As such - are there any plans around to expose a polling method available within the SDK to preserve the current behaviour? I can certainly see the desire for the SDK to return the current state - however polling until the resource is ready is also a really handy function of the SDK at this point :)

Thanks!

**Comment by jhendrixMSFT** [comment]
This was something I was thinking about last week.  Adding a method to the future that waits until completion would be pretty trivial, @tombuildsstuff would this work for you?

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT yep, that would be great 👍

**Comment by jhendrixMSFT** [comment]
This has been added in go-autorest v9.4.0.
