### ISSUE TITLE
no unit test for token.go

### ISSUE THREAD

**Issue by metacpp** [Azure/go-autorest#199]
There's no any unit test existing for token.go file, please create one.

**Comment by metacpp** [comment]
@marstr please assign this issue to me, I will add a unit test separately  for AccessTokensPath method in token.go.

**Comment by mcardosos** [comment]
Hello ! @metacpp 
Are you still working on this?

**Comment by metacpp** [comment]
@mcardosos Yes, just very busy this week.

**Comment by joshgav** [comment]
hi @metacpp have you been able to make progress on this? Thanks!

**Comment by joshgav** [comment]
We have these tests as far as we know, so we will close. @metacpp if you'd like can you open a new issue describing the exact test you'd like?
