### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by tianon** [Azure/go-autorest#2]
Any chance we could get a newer release tag with some of the updates that have hit master since `v0.1-alpha`? :smile:

**Comment by brendandixon** [comment]
@tianon We're still trying to figure out a sound tagging strategy for this package. As soon as we have something worked out, I'll update this and, of course, apply a new tag. :)

**Comment by tianon** [comment]
Ok, fair enough! Thanks for the update. :)

**Comment by ahmetalpbalkan** [comment]
We have tags now for a while, we can probably close this.
