### ISSUE TITLE
Resource Provider Registration opt-out?

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/go-autorest#210]
👋 

I've been taking a look at the code changes between SDK v11.1 and v11.2 - I've noticed that the SDK's/Go-AutoRest's been updated to automatically attempt to register a Resource Provider if a `Resource Provider Not Registered` error is returned.

Sometimes users opt to run Terraform under a low-privilege account, without permission to register Resource Providers (such as when these are whitelisted by a central team, for example) - as such we currently support an environment variable to skip attempting Resource Provider registration, since any attempts to do this will fail. This would allow errors to be raised more quickly when they're expected (and also not waste any additional API Rate Call Limits).

Whilst the code will only attempt this call a single time, it's still an extra HTTP call / delay that would be nice to avoid if possible. As such - would it make sense to have a property on each client to skip Resource Provider registration in order to support this?

WDYT @marstr / @jhendrixMSFT / @mcardosos

Thanks! :)

**Comment by jhendrixMSFT** [comment]
This functionality has been added in go-autorest v9.5.0 which will ship as part of the v12.0.0 SDK.

**Comment by jhendrixMSFT** [comment]
Note there was a bug in the implementation that has been fixed in v9.5.1, so please be sure to pick up v9.5.1 instead.
