### ISSUE TITLE
rename autorest/adal

### ISSUE THREAD

**Issue by joshgav** [Azure/go-autorest#238]
rename `autorest/adal` to `autorest/auth` or similar per request from Azure AD team

**Comment by joshgav** [comment]
cc @navyasric

**Comment by jhendrixMSFT** [comment]
Renaming it breaks customers while providing little value.  I think this is something we should address when we switch to the pipeline model.
 
As a side-note, I haven’t looked at the cited implementations but do keep in mind that Go isn’t an OO language like Java/.NET so the constructs don’t always cleanly map and you can end up shoving square pegs through round holes (Jeff and I grappled with this quite a bit when we wrote the new storage package).  I’m all for consistency as long as the Go implementation remains idiomatic.

**Comment by navyasric** [comment]
@jhendrixMSFT I understand and agree that Go implementation has to be idiomatic and follow the language specific patterns. The feedback about aligning the API surface was more in terms of naming of the concepts introduced in the library. One such example is NewServicePrincipalToken in autorest/adal whereas in ADAL the concept exposed to developer is an AuthenticationContext and the service principal is abstracted. Hope this helps to clarify.

**Comment by jhendrixMSFT** [comment]
For Go the abstraction is the [Authorizer](https://github.com/Azure/go-autorest/blob/master/autorest/authorization.go#L38) interface.  I agree it would be good to align the concepts and we can address this later in the year (summer time-frame) when we refactor our runtime lib and can take large breaking changes however right now we cannot introduce this as it would break all of our customers for no perceived benefit.

**Comment by joshgav** [comment]
Per offline conversation with @navyasric we propose keeping the package name as is in this library since we'd break so many users (like [Kubernetes](https://github.com/kubernetes/kubernetes/blob/a9cceacdaea72d505d8827521f70123c8c2bbd73/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go) and [Terraform](https://github.com/terraform-providers/terraform-provider-azurerm/blob/1005762a37e67f93aa340b40d1682f70523da61a/azurerm/helpers/authentication/access_token.go#L15)).

Instead, we'll provide clear documentation in the SDK README and this repo to clarify that this library is maintained by the Azure Go team.

And we'll still plan to address #239 for our next major release in the summer.

cc @salameer

**Comment by joshgav** [comment]
opened #247 for updating the README, closing this issue now. thanks!
