### ISSUE TITLE
refactor autorest/adal to be more like other ADALs

### ISSUE THREAD

**Issue by joshgav** [Azure/go-autorest#239]
refactor auth library to use AuthenticationContext.AcquireToken*() style methods like other ADALs, e.g. https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/website_sample.py#L107-L115

**Comment by joshgav** [comment]
cc @navyasric

**Comment by jhendrixMSFT** [comment]
We won't be refactoring this library, any changes would need to be made in a new side-by-side library.
