### ISSUE TITLE
Concurrency safety of bearer token authorizer / service principal token?

### ISSUE THREAD

**Issue by krancour** [Azure/go-autorest#240]
My team has noticed a possible race between code that uses (e.g. authorizer) or refreshes (replaces) the actual token that is wrapped by a `ServicePrincipalToken`, since these code segments seem not to be synchronizing with one another.

This line is most illustrative of our concern:

https://github.com/Azure/go-autorest/blob/c2a68353555b68de3ee8455a4fd3e890a0ac6d99/autorest/adal/token.go#L632

Note: I suppose there's a question of "does it matter?" If at any moment, there's the possibility that an authorizer is using one token or another, it _might_ not matter as long as they're both valid at that point in time. But whether that is true or not is determined by whether or not the oauth provider expires the old token upon refresh. Even supposing it does not, ideally, we shouldn't rely on that implementation detail of the oauth provider to spare us from the hazards of this race.

cc @jhendrixMSFT

**Comment by jhendrixMSFT** [comment]
Fixed in v9.9.0.

**Comment by krancour** [comment]
@jhendrixMSFT thanks for fixing this so quickly.

I am curious whether there is still a secondary race. Suppose that in one goroutine, an outbound HTTP request has been fully prepared by the authorizer using one token we can call `x`, but that request hasn't been submitted yet. Meanwhile, another goroutine refreshes the token, resulting in `x'`. Back in the first goroutine, the outbound HTTP request is now using an old token.

Question: Is the old token `x` still valid even after `x'` has been issued? Or is it immediately invalidated? If immediately invalidated, is there then another race here where a fully prepared request can fail authentication because another concurrent process refreshed the token?

**Comment by krancour** [comment]
Also-- separate question unrelated to the RPC-- is there still race between the code that refreshes tokens and the code (e.g. authorizer) that uses them?

**Comment by jhendrixMSFT** [comment]
@krancour Regarding your first comment you are correct, the token is read outside the lock so the fix is incomplete.  I will look into the second issue as I don't know the answer.

**Comment by jhendrixMSFT** [comment]
I would add though that for the second case if the request fails due to the token having been expired during a refresh the retry logic will kick in and attempt the request again (not ideal but there should be no perceived error).

**Comment by jhendrixMSFT** [comment]
@devigned I don't suppose you know what happens in regards to this (see above for the full context).

> Question: Is the old token x still valid even after x' has been issued?

**Comment by krancour** [comment]
> the retry logic will kick in and attempt the request again

It wasn't clear to me what kind of retry logic might be in play. If this is the case, this is probably good enough.

**Comment by devigned** [comment]
@jhendrixMSFT I think the old token is still good pending it hasn't expired. The credentials don't get revoked when requesting a refresh of a token, it's just another token with a new timespan.

**Comment by krancour** [comment]
@devigned good to know. Thanks.

**Comment by jhendrixMSFT** [comment]
Fixed in v10.0.0.

**Comment by HackToHell** [comment]
Still running into the same issue on `v11.3.1` with the EnsureFreshWithContext(). This happens when I have the same client running on two different goroutines and they make a request around the same time.

**Comment by jhendrixMSFT** [comment]
@HackToHell how are you creating your client and authorizer, do you have some sample code?

**Comment by HackToHell** [comment]
@jhendrixMSFT Very sorry, unfortunately one of the azure clients was wrongly initialized leading to this confusion. I can indeed confirm that this doesn't happen anymore when the Authorizer is properly initialized and shared.
