### ISSUE TITLE
Add key vault dataplane authorizer

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/go-autorest#256]
The key vault [dataplane sample](https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/keyvault/operations.go) uses a custom authorizer defined in the sample helper lib [here](https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/4559164aef694aad3b11d9cd76bde6ea008e72c8/iam/oauth.go#L194).  Seems like this should be productized in go-autorest.

**Comment by vladbarosan** [comment]
Seems here just some duplicate logic from go-autorest. Should be fixed when we get do https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/92

**Comment by vladbarosan** [comment]
@mcardosos feel free to close this as a duplicate if you want or wait until Azure-Samples/azure-sdk-for-go-samples#92 is fixed
