### ISSUE TITLE
ADAL operations should accept context where HTTP requests are made

### ISSUE THREAD

**Issue by devigned** [Azure/go-autorest#266]
Calling refresh on a token doesn't require a context today even though it may be long running. I would expect a context to be passed to this and anything that calls the function.

https://github.com/Azure/go-autorest/blob/9ad9326b278af8fa5cc67c30c0ce9a58cc0862b2/autorest/adal/token.go#L590

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.7.0
