### ISSUE TITLE
Specified KeyVaultEndpoint can't be used as resource/audience when asking for access tokens.

### ISSUE THREAD

**Issue by pareshverma91** [Azure/go-autorest#272]
go-autorest/autorest/azure/environments.go specifies KeyVaultEndpoint as https://vault.azure.net/. However, if this is used as the resource to get access token (service principal with client id and secret id), then the obtained access token is rejected by key vault service.
If instead https://vault.azure.net is used as the resource for obtaining the access token, then that access token is accepted by the key vault service. Note that the resource urls differ in trailing slash.
This was quite a time sink :(

**Comment by jhendrixMSFT** [comment]
This has come up before, see https://github.com/Azure/go-autorest/issues/145.  In some cases the endpoint and resource are identical which makes it extra confusing.  For cases where you don't have the resource up front you can use a bearer authorizer callback, see https://github.com/Azure/go-autorest/pull/156 for more details.

**Comment by mcardosos** [comment]
Fixed!

**Comment by jhendrixMSFT** [comment]
The new authorizer is in https://github.com/Azure/azure-sdk-for-go/releases/tag/v16.1.0
