### ISSUE TITLE
The retry for MSI token doesn't follow the retry guidance

### ISSUE THREAD

**Issue by bingosummer** [Azure/go-autorest#276]
It seems that the retry in https://github.com/Azure/go-autorest/pull/269 is different from the retry guidance in the MSI doc.
https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/how-to-use-vm-token#retry-guidance

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.9.1
