### ISSUE TITLE
NewClientWithUserAgent changes DefaultClient

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/go-autorest#28]
https://github.com/Azure/go-autorest/blob/aae6399e6aa1360bae16aa3945f1badd7e0a811c/autorest/client.go#L102

and 

https://github.com/Azure/go-autorest/blob/aae6399e6aa1360bae16aa3945f1badd7e0a811c/autorest/client.go#L134-L138

I feel like if this method gets called multiple times with different userAgent strings, they will all have the same user agent string. The solution might be GetDefaultClient() that returns a client.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Ouch! Good catch! I'll make a quick change / PR.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Actually, my earlier statement is incorrect. NewClientWithUserAgent returns a shallow copy that is safe to modify. I just submitted a PR adding a test to verify / ensure this statement remains true.

**Comment by ahmetalpbalkan** [comment]
heh I'm actually not sure what Go rule is causing the shallow copy behavior. you're right.

**Comment by colemickens** [comment]
DefaultClient isn't a pointer, so this is (shallow) copying:

https://github.com/Azure/go-autorest/blob/aae6399e6aa1360bae16aa3945f1badd7e0a811c/autorest/client.go#L135

Right?

**Comment by ahmetalpbalkan** [comment]
I didn't know that. I thought shallow copy occurs only on passing a struct value to a method.

**Comment by brendandixon** [comment]
@ahmetalpbalkan @colemickens Here's a brief post: http://giantmachines.tumblr.com/post/51007535999/golang-struct-shallow-copy.

**Comment by ahmetalpbalkan** [comment]
wow that's just crazy. but if I do:

	var cat2 *Cat
	cat2 = cat1

then it doesn't do a shallow copy. what a pitfall.

**Comment by ahmetalpbalkan** [comment]
I take it back, it still does.
