### ISSUE TITLE
Responders are not passing back errors

### ISSUE THREAD

**Issue by dramich** [Azure/go-autorest#286]
An easy way to reproduce this is to attempt to use the user client to get a user with a known bad object ID:

```go
userClient.Get(ctx, "badID")
```

When reading the response body without the responder the error is present:
```json
{
  "odata.error": {
    "code": "Request_ResourceNotFound",
    "message": {
      "lang": "en",
      "value": "Resource 'badID' does not exist or one of its queried reference-property objects are not present."
    }
  }
}
```

The error returned through the responder:
`graphrbac.UsersClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error"`

**Comment by jhendrixMSFT** [comment]
Hmm it looks to me that the error object doesn't conform to the [OData spec](http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html#_Toc372793091).

**Comment by jhendrixMSFT** [comment]
According to the RP this service returns error objects that conform to OData v3, whereas our runtime assumes OData v4.

**Comment by dramich** [comment]
That makes sense. Can we have the error bubbled up in whole even if it doesn't match spec?

**Comment by jhendrixMSFT** [comment]
That's what I'm looking at now, hopefully I'll have a PR later today.

**Comment by jhendrixMSFT** [comment]
This has been fixed in https://github.com/Azure/go-autorest/releases/tag/v10.11.3

**Comment by dramich** [comment]
Thanks @jhendrixMSFT, this is great.
