### ISSUE TITLE
Provide helper to read auth file

### ISSUE THREAD

**Issue by elyscape** [Azure/go-autorest#287]
Versions of the package prior to 10 exposed [a function called `GetClientSetup`][GetClientSetup] that would parse an auth file and return [a struct][ClientSetup] containing an authorizer, the resource base URI, and the contents of the auth file, critically including the subscription ID and the tenant ID. With version 10, it was replaced by [a function called `NewAuthorizerFromFile`][NewAuthorizerFromFile], which parses an auth file and returns an authorizer. While this is definitely simpler, it unfortunately also means that retrieving the resource base URI, subscription ID, and tenant ID is now left to the client. It would be nice if the old `GetClientSetup` function, or something equivalent, were brought back to simplify this.

[GetClientSetup]: https://github.com/Azure/go-autorest/blob/v9.10.0/autorest/azure/auth/authfile.go#L56-L98
[ClientSetup]: https://github.com/Azure/go-autorest/blob/v9.10.0/autorest/azure/auth/authfile.go#L34-L40
[NewAuthorizerFromFile]: https://github.com/Azure/go-autorest/blob/v10.0.0/autorest/azure/auth/auth.go#L104-L143

**Comment by elyscape** [comment]
Actually, after doing some more digging, it would also be nice to have a way to get the resource base URI, subscription ID, and tenant ID determined when calling `NewAuthorizerFromEnvironment`. This would allow clients to delegate determination of these fields entirely to the SDK, instead of having to replicate the relevant logic in their own code.

**Comment by joshgav** [comment]
Thanks @elyscape for pointing this out. We'll try to add this when we next refactor service principal auth.

**Comment by elyscape** [comment]
Awesome, thanks! Do you have a vague idea as to when that might happen?

**Comment by jbw976** [comment]
I would also love to see this functionality.  The flow of creating an auth file via `az ad sp create-for-rbac --sdk-auth` and then programmatically loading it with `auth.NewAuthorizerFromFile` is pretty smooth, but that doesn't directly give you the `subscriptionID` which you need to create most every service client.

Is there a recommended approach for the time being? If we need to directly ask the user for their `subscriptionID` in addition to their auth file, is the `subscriptionID` a value that needs to be protected? (e.g., store it in a Kubernetes secret).

**Comment by elyscape** [comment]
@joshgav Just checking in on this to see if there's been any progress on a solution or prioritization of one. Thanks!

**Comment by jhendrixMSFT** [comment]
Sorry for the delay, the changes in v11.5.0 now make the configuration info available.  Here's an example of how it now works.
```go
settings, err := auth.GetSettingsFromEnvironment()
// or settings, err := auth.GetSettingsFromFile()
if err != nil {
	panic(err)
}
client := redis.NewClient(settings.GetSubscriptionID())
client.Authorizer, err = settings.GetAuthorizer()
if err != nil {
	panic(err)
}
```
