### ISSUE TITLE
DoRetryWithRegistration: unable to unwrap error due to use of fmt.Errorf

### ISSUE THREAD

**Issue by grrtrr** [Azure/go-autorest#291]
_I am running into a problem of extracting API errors, hindered by the use of fmt.Errorf instead of Azure error type in `DoRetryWithRegistration()`._

### Problem Description 
A good point in the Azure SDK design is the use of error interfaces, as well as built-in support for the [`Cause()` interface](https://godoc.org/github.com/pkg/errors#hdr-Retrieving_the_cause_of_an_error) of the `pkg/errors` package.

This makes it possible to _unwrap_ errors to extract added context that might not be useful to show to the end user, e.g.
```go
if se, ok := err.(*azure.ServiceError); ok {       
      // do something with se.Code and/or se.Message
} else  {
    // use errors.Cause() to extract the actual cause of the error
}
```

***Unfortunately this elegant idea is broken as soon as there is a single `fmt.Errorf()` in the chain.*** At that moment, the type of the error becomes `errors/errors.go:errorString`, losing all the elegant advantages of the design.

As a result, we get long error messages from which we are unable to extract the relevant cause/details:
```
Jun 18 14:02:18 service: Error: [pgdelete.go:185] failed to remove Azure disks: failed request: \
autorest/azure: Service returned an error. \
Status=<nil> \
Code="OperationNotAllowed" \
Message="Disk testfailover-ca2grrt-w08-131-5b280475-6ff575217b38efdbc-OSDisk is attached to VM /subscriptions/34756967-9f64-4a4a-93b3-06a39270919/resourceGroups/Gerrit/providers/Microsoft.Compute/virtualMachines/testfailover-ca2grrt-w08-131-5b280475-6ff575217b38efdbc."
```

The `failed request:` comes from 
```go
// go-autorest/autorest/azure/rp.go

// DoRetryWithRegistration tries to register the resource provider in case it is unregistered.
// It also handles request retries
func DoRetryWithRegistration(client autorest.Client) autorest.SendDecorator {
        // ...
        return resp, fmt.Errorf("failed request: %s", err) // <=== PROBLEM HERE
```
The 'failed request' information does not add any new important detail, the use of fmt.Errorf breaks the chain of wrapped Azure error interfaces.
Without it, we would be able to extract `Code` and act correspondingly on `OperationNotAllowed`, perhaps offering the user guidance and context-dependent information.
Due to the wrapping in fmt.Errorf, we no longer have this ability.

### Requested Improvement

Can you please simply change the above to
```go
return resp, err
```
This would expose the Azure error `err` to the caller and fix the problem.

**Comment by jhendrixMSFT** [comment]
This has been fixed in https://github.com/Azure/go-autorest/releases/tag/v10.11.3

**Comment by grrtrr** [comment]
Thank you for looking into this and the quick response.
