### ISSUE TITLE
include BaseURI and SubscriptionID in autorest.Client

### ISSUE THREAD

**Issue by joshgav** [Azure/go-autorest#295]
`BaseURI` and `SubscriptionID` fields are added to all of our RP-specific clients, but because they aren't part of `autorest.Client` they can't be manipulated by helper functions intended to generically handle all RP-specific clients.

Can we move the BaseURI and SubscriptionID fields into `autorest.Client`?

Thanks!

**Comment by joshgav** [comment]
cc @anguslees

**Comment by marstr** [comment]
My initial thought is that BaseURI may be harmless to move up into the autorest.Client type. However, subscription ID should remain in only Azure management-specific clients. It is an Azure introduced concept after all. :)

**Comment by jhendrixMSFT** [comment]
Closing as we won't be doing this for track 1.
