### ISSUE TITLE
emit traces when env var set

### ISSUE THREAD

**Issue by joshgav** [Azure/go-autorest#298]
Can we add a way (or two) to request traces via configuration?

Today, getting traces requires source modifications as described in [the SDK README](https://github.com/Azure/azure-sdk-for-go#inspecting-and-debugging). That is difficult and sometimes not possible, e.g. when we're embedded in a tool as in Azure/azure-sdk-for-go#1828.

The SDK should emit more raw trace data to stderr when an environment variable is set for the sake of support and troubleshooting. A potential scheme could be to check the env var `AZURE_GO_SDK_LOG_LEVEL=[0|1|2]`, with 0 meaning log nothing; 1 meaning log URLs and headers; and 2 meaning log URLs, headers, and bodies.

This should be alongside OpenTracing or OpenCensus spans if/when we add them, meaning I think we still need raw traces sometimes. We can use the same mechanism for both if that makes sense.

Thoughts?

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.15.0
