### ISSUE TITLE
add user-agent to IMDS/MSI calls

### ISSUE THREAD

**Issue by joshgav** [Azure/go-autorest#300]
https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L645

Can we add a user-agent string identifying the Go SDK to the above ^ HTTP request? Is it included some other way? This is to help us review telemetry from the IMDS API. Thanks!

**Comment by joshgav** [comment]
Let's use "go-autorest/version".

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.14.0
