### ISSUE TITLE
Improve refreshing the refresh token scenario

### ISSUE THREAD

**Issue by vladbarosan** [Azure/go-autorest#304]
Right now when the refresh token becomes invalid for whatever reason ( e.g. is expired or is revoked )
the only way to do that is to create a new authorizer, assign it to the client and retrying the call. 

We should look if we can automate a retry logic on `TokenRefreshErrror` or at least expose a way to retrigger the auth flow without having to create a new authorizer.

**Comment by vladbarosan** [comment]
@joshgav  can you consult with AAD team what they recommend to do when the refresh token is expired ? Should we automatically try to get a new one or leave it to the consumers of the SDK to explicitly obtain a new one ?

**Comment by jhendrixMSFT** [comment]
This has been implemented for track 2 in azidentity, we won't be back-porting it to track 1.
