### ISSUE TITLE
Validation tricked by non-nil-able value passed in

### ISSUE THREAD

**Issue by marstr** [Azure/go-autorest#307]
As discovered by @hbuckle in Azure/azure-sdk-for-go#2445, both types `FactoryVSTSConfiguration` and `*FactoryVSTSConfiguration` satisfy the interface `BasicFactoryRepoConfiguration`. (Source file can be [found here](https://github.com/Azure/azure-sdk-for-go/blob/4e8cbbfb1aeab140cd0fa97fd16b64ee18c3ca6a/services/datafactory/mgmt/2018-06-01/datafactory/models.go)).

Because Validation is implemented using reflection, the compiler isn't helping us distinguish between the two types, we have to wait until runtime. Furthermore, because Validation assumes that RepoConfiguration is always passed in as a pointer, when a struct is passed in it always fails.

There are two possible solutions:
- Update code-gen to only dangle these off of the pointer type. (This could conceivably cause breaking changes)
- Update the Validation code to ensure the value isn't a struct, before asserting that the object isn't a nil pointer.

**Comment by jhendrixMSFT** [comment]
We won't be fixing this for track 1.  Not applicable for track 2 as we won't be generating client-side validation.
