### ISSUE TITLE
API error re: duplicate identifierUris

### ISSUE THREAD

**Issue by kalafut** [Azure/go-autorest#308]
While testing under high concurrency, I'm occasionally seeing this response during the CreateApplication portion:

`graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2018-08-09T17:38:27","message":{"lang":"en","value":"Another object with the same value for property identifierUris already exists."},"requestId":"bd30e6f2-b6fd-4b0f-b490-8134d23551d8","values":[{"item":"PropertyName","value":"identifierUris"},{"item":"PropertyErrorCode","value":"ObjectConflict"}]}}]`

The code to request the App creation is very simple and I'm not seeing how a duplicate identifierUri is getting in here:

```
func (c *client) createApp(ctx context.Context) (app *graphrbac.Application, err error) {
	name, err := uuid.GenerateUUID()
	if err != nil {
		return nil, err
	}

	name = appNamePrefix + name

	appURL := fmt.Sprintf("https://%s", name)

	result, err := c.provider.CreateApplication(ctx, graphrbac.ApplicationCreateParameters{
		AvailableToOtherTenants: to.BoolPtr(false),
		DisplayName:             to.StringPtr(name),
		Homepage:                to.StringPtr(appURL),
		IdentifierUris:          to.StringSlicePtr([]string{appURL}),
	})

	return &result, err
}
```

**Comment by jhendrixMSFT** [comment]
@kalafut sorry for the delay on this.  Is this still an issue?

**Comment by kalafut** [comment]
I can't really say for sure. We ended up wrapping the call in some retry logic and I've not set up the high concurrency test again (and am not really inclined to). This hasn't cropped up in any other ways either, so I'm fine if you want to close it.

**Comment by jhendrixMSFT** [comment]
The only thing that comes to mind is if `uuid.GenerateUUID()` is poorly implemented and generates repeating sequences (not sure if you already looked into this possibility).  At any rate since this is no longer an issue I will close for now.

**Comment by kalafut** [comment]
That call is pretty solid (it's our common source of crypto-usable UUIDs).
