### ISSUE TITLE
Environments should expose Data Lake URI's

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/go-autorest#312]
👋 

It'd be really handy for the Data Lake URI to be exposed as part of the Environments struct:

https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L37-L58

An example URI for Azure Public is `adl://tomdevdls1.azuredatalakestore.net/test/example.txt`, so I'd expect the domain `azuredatalakestore.net` to be exposed as part of the Environments struct. Would it be possible to expose this information?

Thanks!

**Comment by tombuildsstuff** [comment]
I've just noticed this is currently exposed on the Client within the SDK, which we should be able to use in the interim: https://github.com/Azure/azure-sdk-for-go/blob/master/services/datalake/store/2016-11-01/filesystem/client.go#L29

**Comment by jhendrixMSFT** [comment]
@joshgav do you know if there are endpoints for the sovereign clouds?

**Comment by marstr** [comment]
Putting this back in the triage bucket now that I've been re-orged.

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest@v0.11.26`
