### ISSUE TITLE
autorest.DoRetryForStatusCodes infinitely retries on http.StatusTooManyRequests statuscode

### ISSUE THREAD

**Issue by awesomenix** [Azure/go-autorest#322]
Function autorest.DoRetryForStatusCode has this piece of code 

```
// don't count a 429 against the number of attempts
				// so that we continue to retry until it succeeds
				if resp == nil || resp.StatusCode != http.StatusTooManyRequests {
					attempt++
				}
```
Basically infinitely retries in case of backoff, sometimes, though there is an opportunity for caller to cancel, the library should be flexible enough for client to provide a feature if the infinite retry feature is required.

**Comment by awesomenix** [comment]
Created PR: https://github.com/Azure/go-autorest/pull/323

**Comment by jhendrixMSFT** [comment]
Per discussion in https://github.com/Azure/go-autorest/pull/323 `DoRetryForStatusCodes` will be fixed to return the last response when the context is cancelled.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.15.5.
