### ISSUE TITLE
Race in DoRetryForStatusCodes sender

### ISSUE THREAD

**Issue by mxk** [Azure/go-autorest#333]
`autorest.Preparer` and `autorest.Responder` interfaces both explicitly say that the implementations "may be shared and re-used." The same is not said for `autorest.Sender`, but it's not clear to me whether that's an oversight in documentation or if the rules for senders are different.

Currently, the sender returned by `DoRetryForStatusCodes` decorator increments the `attempts` argument, which causes a race if multiple goroutines share the same sender. I'm not sure if there is an actual reason why this increment needs to happen as part of the execution rather than in the outermost function:

https://github.com/Azure/go-autorest/blob/ea233b6412b0421a65dc6160e16c893364664a95/autorest/sender.go#L214-L219

Either way, the documentation for `autorest.Sender` should be updated to say whether the implementations can or cannot be shared and re-used. Ideally, this race should be fixed to allow more efficient operation by reusing senders.

**Comment by jhendrixMSFT** [comment]
@mxk it's not clear from your description where the race is, can you please clarify?

**Comment by mxk** [comment]
Sure, run the following with `go test -race`:

```go
package main

import (
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"

	"github.com/Azure/go-autorest/autorest"
)

func TestDoRetryForStatusCodes(t *testing.T) {
	s := httptest.NewServer(http.HandlerFunc(func(http.ResponseWriter, *http.Request) {}))
	defer s.Close()

	sender := autorest.DecorateSender(s.Client(),
		autorest.DoRetryForStatusCodes(0, 0, http.StatusRequestTimeout))

	var wg sync.WaitGroup
	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			req, _ := http.NewRequest(http.MethodGet, s.URL, nil)
			if _, err := sender.Do(req); err != nil {
				t.Fatal(err)
			}
		}()
	}
	wg.Wait()
}
```

The `attempts` argument to `DoRetryForStatusCodes` becomes shared state, preventing the `sender` in my example from being used concurrently or even reused for multiple requests.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v11.2.5.
