### ISSUE TITLE
add helper methods to check for common error types

### ISSUE THREAD

**Issue by joshgav** [Azure/go-autorest#336]
### Feature Request

Add helper methods to easily check for common error types, e.g.

```
IsBadRequest(err) // 400
IsNotFound(err)  // 404
IsUnauthorized(err)  // 401
IsServiceUnavailable(err)  // 503
```

**Comment by joshgav** [comment]
cc @cpuguy83 @khenidak

**Comment by cpuguy83** [comment]
Cool, I think for autorest it'd probably be ok to have something generic like `IsHTTPStatus(err, <code>)` just because when working on autorest you expect HTTP and HTTP status codes.

**Comment by cpuguy83** [comment]
It's in the azure go-sdk packages that less generic things would be needed.

**Comment by jhendrixMSFT** [comment]
Helper methods added in https://github.com/Azure/go-autorest/releases/tag/v12.2.0
