### ISSUE TITLE
Split convert package out into its own repository

### ISSUE THREAD

**Issue by katbyte** [Azure/go-autorest#340]
We would like to use the [convert](https://github.com/Azure/go-autorest/tree/master/autorest/to) package in the terraform azure provider, however could it be broken out into its own repo?

**Comment by jhendrixMSFT** [comment]
How close is Terraform to adopting modules?  I'm working on splitting up `go-autorest` into multiple modules and can make this package its own module.

**Comment by katbyte** [comment]
Fairly close tbh. I still have to try out modules (and will be as part of us adopting them) but I think that would work for us.

**Comment by jhendrixMSFT** [comment]
Awesome.  I'm going to close this issue then as I'm tracking the module work in https://github.com/Azure/go-autorest/issues/327.
