### ISSUE TITLE
LoadProfile should honor $AZURE_CONFIG_DIR setting

### ISSUE THREAD

**Issue by russt** [Azure/go-autorest#345]
Currently `autorest/azure/cli/profile.go` hard-codes location of `.azure` profile `~/.azure/azureProfile.json`

It should instead honor `AZURE_CONFIG_DIR` setting as per [microsoft docs](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-file)

Workaround is to copy `$AZURE_CONFIG_DIR` to user home, e.g.:
```
cp -rp $AZURE_CONFIG_DIR ~/.azure
```

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v11.2.4.  Thanks for reporting this issue.
