### ISSUE TITLE
Autorest validation does not accept numbers in resource group name

### ISSUE THREAD

**Issue by seyadava** [Azure/go-autorest#348]
This is the error returned by go-autorest:
Cannot create resource group. Error details: resources.GroupsClient#CreateOrUpdate: 
Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=Pattern 
value="ascansubscrrg395" details: value doesn't match pattern ^[-\p{L}\._\(\)]+$

**Comment by jhendrixMSFT** [comment]
Introduced in https://github.com/Azure/azure-sdk-for-go/issues/3114, need to add `\w` to the regex.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v22.1.0.
