### ISSUE TITLE
Get binary file in Golang

### ISSUE THREAD

**Issue by msyihchen** [Azure/go-autorest#351]
Do you support getting binary file in golang? It looks like it always tries to do json unmarshalling which would fails if response is a binary file.

**Comment by jhendrixMSFT** [comment]
It depends on the API, short answer is yes the APIs that send/receive a binary file take an `io.ReadCloser` as an argument.  Is there an API you're using that is incorrectly trying to marshal binary data as JSON?

**Comment by jhendrixMSFT** [comment]
Please re-open if you have further questions.
