### ISSUE TITLE
Tracing with opencensus: questions

### ISSUE THREAD

**Issue by lmolkova** [Azure/go-autorest#354]
I'm working on Azure Application Insights and Opencensus in Microsoft and was going to ask you guys to implement tracing with opencensus (or contribute this), so this is great to learn this has already been done!

I have a couple of questions I hope you can help me to clarify.

1. I noticed there is [async.DoneWithContext](https://github.com/Azure/go-autorest/blob/4e5fffdf007df29ed0862f9e01fafabf4396e851/autorest/azure/async.go#L96), that creates spans.
Who calls this function? Is it particular Azure SDK? If so, I'd expect it would be their responsibility to instrument their calls and have polling tracked?

2. [tracing.EnableWithAIForwarding](https://github.com/Azure/go-autorest/blob/528b76fd0ebec0682f3e3da7c808cd472b999615/tracing/tracing.go#L96). Setting up exporter is part of user application configuration.  They choose where to send data and configure exporter similar to https://github.com/Microsoft/ApplicationInsights-LocalForwarder/blob/master/examples/opencensus/go-app/main.go#L26. 
This is a typical opencenus usage. Libraries are not expected to configure exporters - otherwise, it may be hard to control all settings and does not scale for all possible exporters users would want to bring.
It's also app-specific where the data is sent to, all libraries and user code should have common exporter.
So I'd suggest deprecating this method to avoid confusion and future maintenance cost.

**Comment by vladbarosan** [comment]
Hi @lmolkova , thanks for the questions.
1. `DoneWithContext` ( like `Done`) is a call that users would make to check if their `Future` is completed. While the Azure SDK is using Futures, those can be used outside of the SDK's.

2. Generally I agree with this. We went with introducing this as a way to easily integrate with the AppInsights Forwarder. We can check with @joshgav if we want to keep this going forward. Thanks for the feedback on this one.
