### ISSUE TITLE
report attempts and errors in NewAuthorizerFromEnvironment chain

### ISSUE THREAD

**Issue by joshgav** [Azure/go-autorest#359]
A user (@asw101) wants to use a device code authorizer when the others in [NewAuthorizerFromEnvironment](https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go#L44) fail in some circumstances.

Can we aggregate attempts and errors from each authorizer tried in the chain? And print that out when all fail? That would at least provide basic info the user could parse and make a decision based on.

Can we provide a way to append or replace authorizers? To create a custom chain? That would be another way to address.

**Comment by jhendrixMSFT** [comment]
In https://github.com/Azure/go-autorest/releases/tag/v11.5.0 the primitives used to build `NewAuthorizerFromEnvironment()` have been exported so you can build your own authorization chains including device code.  Take a look at [EnvironmentSettings.GetAuthorizer()](https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go#L203) for details.
