### ISSUE TITLE
Expose 'CosmosDBDNSSuffix' in the Environments struct

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/go-autorest#366]
👋 

We're working through scoping out what's needed to add support for CosmosDB Collections & Databases into Terraform. As a part of the investigation here we've noticed that there's no suffix available as part of the Environment struct for the CosmosDB DNS Suffix, [as there is for example for Container Registries etc](https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L37-L57).

Would it be possible to add a new property to the Environments struct which exposes the CosmosDB DNS Suffix?

Thanks!

**Comment by vladbarosan** [comment]
Hi @tombuildsstuff , yes we can add it. One thing also I noticed is that the container registry endpoint is wrong for the government clouds. will fix.
