### ISSUE TITLE
`dep` dependencies broken for github.com/census-instrumentation/opencensus-proto

### ISSUE THREAD

**Issue by DrEsteban** [Azure/go-autorest#375]
The latest version of this package fails to build when pulled in via `dep ensure` due to a breaking change pushed by one of your dependencies.

**Example Repro**
https://github.com/DrEsteban/Azure-go-autorest-repro
(Repro steps included in README)

**Workaround**
I needed to manually specify a dep [[override]] as follows:
```
[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  version = "0.1.0"
```

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v11.6.1.  Thanks for reporting this issue.
