### ISSUE TITLE
Implement password credentials flow for federated users

### ISSUE THREAD

**Issue by nugasescuserbun** [Azure/go-autorest#378]
Currently the password credentials flow works only with managed users, not with federated users. It would be great to have support for the ws-trust exchange for federated users, similarly to how the other adal packages (python, nodejs, net etc) do.

**Comment by aido123** [comment]
Any update on if this is been looked at? Thanks

**Comment by jhendrixMSFT** [comment]
We won't be adding this feature to `go-autorest`.  I've ported this to https://github.com/Azure/azure-sdk-for-go/issues/17615 for consideration in `azidentity`.
