### ISSUE TITLE
Enable interactive user authentication

### ISSUE THREAD

**Issue by farehar** [Azure/go-autorest#382]
Currently there is no support available for interactive user authentication. UserName/Password flow doesn't work if 2FA auth is enabled. It'll be great to have interactive user authentication.

**Comment by colemickens** [comment]
If I understand the ask correctly, interactive authentication that works with 2FA has existed for quite some time: https://github.com/Azure/go-autorest/blob/master/autorest/adal/devicetoken.go#L112

This is the same sort of interactive login that the Azure CLI 2 used to default to, for example.

**Comment by jhendrixMSFT** [comment]
This ask is slightly different than device code auth flow, but is identical to the CLI auth experience (browser is automatically opened and no need to enter a device code).  I have a mock-up of this in my fork, see the [interactive branch](https://github.com/jhendrixMSFT/go-autorest/tree/interactive), `auth.NewAuthorizerFromInteractiveLogon()`.  It's based on the CLI's implementation.

**Comment by colemickens** [comment]
Nice, I'll need that soon too actually. Thanks @jhendrixMSFT!

**Comment by jhendrixMSFT** [comment]
This has been implemented in `azidentity` for track 2.  We won't be back-porting this to track 1.
