### ISSUE TITLE
add support for TLS Renegotiation

### ISSUE THREAD

**Issue by tiraffe** [Azure/go-autorest#384]
I am a developer of Azure Cognitive Services. When I sent a request using this client to our service, I encountered an error: `Failure sending request: StatusCode=0 -- Original Error: Post xxx: local error: tls: no renegotiation`

It seems Golang has supported renegotiation since version 1.7. (https://github.com/golang/go/issues/5742)

I have created a PR to enable renegotiation: https://github.com/Azure/go-autorest/pull/383
Please let me know if any questions.

**Comment by jhendrixMSFT** [comment]
Added in https://github.com/Azure/go-autorest/releases/tag/v11.8.0
