### ISSUE TITLE
Utils removed broken azch-captureorder container

### ISSUE THREAD

**Issue by sumitkute** [Azure/go-autorest#387]
The go-autorest URL github.com/Azure/go-autorest/autorest/utils is being referred in https://github.com/Azure/azch-captureorder Docker file which is part of https://aksworkshop.io/. Its it broken. Please provide alternative what should be used if its deprecated.

**Comment by jhendrixMSFT** [comment]
What functionality were you using from this package?

**Comment by sumitkute** [comment]
I was not using directly.. I am using the azch-captureorder container code for AKS workshop. The container code is referring this path before its removed and the container creation is failing after. I have also raise a issue in https://github.com/Azure/azch-captureorder  to provide a fix as per your new 12.0 release..

**Comment by vermegi** [comment]
I tried out a local dockerfile for https://github.com/Azure/azch-captureorder and removed the github.com/Azure/go-autorest/utils dependency. This seems to work.

**Comment by jhendrixMSFT** [comment]
Closing as this seems to be resolved.  Please reopen if you have further issues.
