### ISSUE TITLE
The func "NewUsernamePasswordConfig" doesn't support China Azure

### ISSUE THREAD

**Issue by azureluo** [Azure/go-autorest#389]
Hi,

When we are doing integration with Azure API, we found the func "NewUsernamePasswordConfig" doesn't support China Azure. And my customer needs to use username and password to do authentication. Could you please help me out?

Thanks,
Jerry

**Comment by jhendrixMSFT** [comment]
You can set this in two different ways depending on your scenario.  See the following code.
```go
func option1() {
	cfg := auth.NewUsernamePasswordConfig("name", "pwd", "clientID", "tenantID")
	cfg.AADEndpoint = azure.ChinaCloud.ActiveDirectoryEndpoint
	cfg.Resource = azure.ChinaCloud.ResourceManagerEndpoint
	cfg.Authorizer()
}

func option2() {
	// set the following environment vars
	// AZURE_USERNAME = "name"
	// AZURE_PASSWORD = "pwd"
	// AZURE_ENVIRONMENT = "AZURECHINACLOUD"
	settings, _ := auth.GetSettingsFromEnvironment()
	cfg, _ := settings.GetUsernamePassword()
	cfg.Authorizer()
}
```
Let me know if this works for you.

**Comment by azureluo** [comment]
Got it. Thank you so much for help.

**Comment by jhendrixMSFT** [comment]
Please re-open if you have further questions.

**Comment by azureluo** [comment]
I still ran into another problem - where can I get the username? I registered a App for Service Principle, other than client ID and client secret, I can't find the username. I tried to use the display name of the registered App and used the authorizer for creating resource group, it threw out the exception of "Failed to refresh the Token for request... ..."AADSTS50034: The user account Microsoft.AzureAD.Telemetry.Diagnostics.PII does not exist....". I tried to use a username from the AD users with client secret of registered App, it threw out the exception "Failed to refresh the Token for request... ...AADSTS50126: Invalid username or password......". Could you please help to take a look.

**Comment by azureluo** [comment]
Sorry, I can't reopen this issue.

**Comment by jhendrixMSFT** [comment]
Get it from the code?  It's on the `UsernamePasswordConfig` type, e.g. `cfg.Username`.
