### ISSUE TITLE
Storage resource id is missing in ResourceIdentifier field of Environment

### ISSUE THREAD

**Issue by feiyushi** [Azure/go-autorest#394]
Please check out this page for the resource id of storage:
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-storage-blobs-and-queues

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v12.1.0
