### ISSUE TITLE
Allow exponential backoffs per API call and/or retry codes

### ISSUE THREAD

**Issue by amanohar** [Azure/go-autorest#398]
An infinite retry on 429 is a bad pattern without an ability to do exponential back offs. Every service is different in terms of how they treat a client when it returns 429s.

In some cases it might count against call limits. And in some cases services might even blacklist a client.

Here is an example of how Key Vault expects clients to retry instead of infinite linear retry:
https://docs.microsoft.com/en-us/azure/key-vault/key-vault-ovw-throttling#how-to-throttle-your-app-in-response-to-service-limits

An important point worth highlighting from the doc:
> failed requests that return a 429 count towards the throttle limits tracked by Key Vault.

Real world example:
40 create certificate calls in 10 secs (KV allows 10 creates per 10 seconds) lead to 3.48K calls because of Go SDK's call pattern. :(

Based on this: https://github.com/Azure/go-autorest/issues/322
>DoRetryForStatusCodes will be fixed to return the last response when the context is cancelled.

This is a stop gap solution. Because now the client has to add retry logic on top of what's provided by SDK.

SDK should also let the caller override retry pattern per API call and/or retry code. This is crucial because each Azure service behaves differently and a single type of call pattern doesn't fit all cases. This is a good solution vs compromise of:

>Write your own sender func that doesn't use DoRetryForStatusCodes but some variant of it, then call *Preparer(), CustomSender(), *Responder() individually.

or

>Cancelling the context.

References:
1) https://github.com/Azure/go-autorest/pull/324/files
2) https://github.com/Azure/go-autorest/issues/322

**Comment by jhendrixMSFT** [comment]
I agree that the design should allow for greater flexibility, allowing callers to override the default retry mechanism at the client and/or API call level.  We have some ideas on how to address this but it's long-lead work items.  In the interim you bring up a good point that the current fix we made for Terraform (infinite retry on 429) bypasses the exponential back-off mechanism which is easy to address.  @tombuildsstuff would this be problematic for Terraform?

**Comment by weinong** [comment]
@jhendrixMSFT any update?

**Comment by jhendrixMSFT** [comment]
I had a chat with @tombuildsstuff and he believes that my above suggested fix would negatively impact Terraform.  I haven't had time to think about this more, off-the-cuff we could add a separate flag to opt-in to this new behavior however I'm not really liking that as the list of flags keeps growing.  Open to suggestions.

**Comment by yangl900** [comment]
Possible to get more insights why it would negatively impact Terraform? It's unclear how instant retry on 429 would be helpful. AFAIK most of the Azure services would keep throttling the client, it only make things worse.

**Comment by jhendrixMSFT** [comment]
For ARM it's not instant retry as, at least in our observations, a `Retry-After` header is returned which the SDK will honor.

**Comment by jhendrixMSFT** [comment]
One idea that wouldn't require a breaking change is the ability to specify a retry policy (in the form of an `autorest.SendDecorator`) in the context object provided to the API; this would give the caller complete control over how a retry is handled.  Thoughts?

**Comment by yangl900** [comment]
The implementation of DelayWithRetryAfter only handles number format of Retry-After, but RFC allows datetime. I wonder if that's why we don't do back off properly sometimes.

https://github.com/Azure/go-autorest/blob/946071b7112e0f046a01908297e5c9f446ff6ce6/autorest/sender.go#L257

```
The Retry-After response-header field can be used with a 503 (Service Unavailable) response to indicate how long the service is expected to be unavailable to the requesting client. This field MAY also be used with any 3xx (Redirection) response to indicate the minimum time the user-agent is asked wait before issuing the redirected request. The value of this field can be either an HTTP-date or an integer number of seconds (in decimal) after the time of the response.

       Retry-After  = "Retry-After" ":" ( HTTP-date | delta-seconds )
Two examples of its use are

       Retry-After: Fri, 31 Dec 1999 23:59:59 GMT
       Retry-After: 120
In the latter example, the delay is 2 minutes.
```

**Comment by yangl900** [comment]
I think a retry policy or callback would be helpful too.

**Comment by jhendrixMSFT** [comment]
The date/time in Retry-After has come up before in a general discussion, I know that Python supports this format but I don't believe other SDKs do.  Does keyvault return a date/time in Retry-After?

**Comment by yangl900** [comment]
I actually don't have a proof what keyvault return. I'd say it would be good to handle both given it is allowed by protocol.

**Comment by feiskyer** [comment]
Got same issues on kubernetes cluster-autoscaler (probably also in other kubernetes projects). When 429 is returned, a single vmssVM LIST would be stuck on a long time (e.g. 15min as we observed).

**Comment by jhendrixMSFT** [comment]
@feiskyer in the case you observed was there a `Retry-After` header in the response?

**Comment by feiskyer** [comment]
@jhendrixMSFT Unfortunately, didn't observe the Retry-After header during my observations (need new code changes to log those headers).

For the retry policy, any plans to support it so that we can switch to it in various projects?

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/go-autorest/releases/tag/v12.3.0, you can now set custom send decorator change in v12.3.0.  The Go SDK will be updated to support this in the next release.  Small sample to use `DoRetryForAttempts` instead of the default `DoRetryForStatusCodes`.
```go
ctx := autorest.WithSendDecorators(context.Background(), []autorest.SendDecorator{autorest.DoRetryForAttempts(5, 5*time.Second)})
_, err = client.List(ctx)
```
