### ISSUE TITLE
Unable to register a resource provider

### ISSUE THREAD

**Issue by atul-mantri** [Azure/go-autorest#401]
I am seeing different error codes for the same workflow of using a resource provider - ContainerInstance to create a new ACI with the same app id, tenant, subscription and resource group.
The error codes are:
1. MissingSubscriptionRegistration
2. SubscriptionNotRegistered

what ends up happening though is we only try to register on the error case 1. The error is also indeterministic, where on each iteration I get different combinations of error 1 or 2. I want to understand under what situation will I get error 1 vs 2.
The Azure-sdk-for-go  version is: 26.5.0
The go-autorest version is 11.5.2

**Comment by jhendrixMSFT** [comment]
Also can you please include the API version and region.

**Comment by atul-mantri** [comment]
Sure.

I called the CreateOrUpdate() API in containergroups.go using the NewContainerGroupsClient.
The APIVersion is "2018-10-01"  and as far as region goes, if you are asking for the Azure Region, then it is "westus".

**Comment by Shuanglu** [comment]
@jhendrixMSFT , just fyi i also raised ICM 122058983 with ACI team regarding this. Feel free to let me know if any help requested from support end.

**Comment by karajas** [comment]
Answered on incident.

**Comment by jhendrixMSFT** [comment]
Closing as stale and was handled via ICM.
