### ISSUE TITLE
adal.ErrDeviceGeneric error response is not actionable

### ISSUE THREAD

**Issue by Devinwong** [Azure/go-autorest#404]
My application ID is 10b55c8d-cec6-4db2-802f-c8c3cc4f5056. I got pre-authorization approval from ARM.
I was able to go through the following screenshots. 
![image](https://user-images.githubusercontent.com/13621569/59185757-d4f0ed00-8ba3-11e9-96ab-d5efd0256e0c.png)
![image](https://user-images.githubusercontent.com/13621569/59185769-dc17fb00-8ba3-11e9-8130-9b80233b7a72.png)
After signed in, I got this error message. _failed to finish device auth flow: autorest/adal/devicetoken: Error while retrieving OAuth token: Unknown Error_
Specifically, it happened when executing the following codes with failure at the bottom line _WaitForUserCompletion_
My code is working correctly when I use Azure CLI's application ID for development purpose. But using my own application ID, I could see this error consistently.

I tried to add followings into code brackets but failed. It just showed as text .

```go
dfc := auth.NewDeviceFlowConfig("10b55c8d-cec6-4db2-802f-c8c3cc4f5056", "common")
fmt.Println("dfc: \n", dfc)

oauthConfig, err := adal.NewOAuthConfig(dfc.AADEndpoint, dfc.TenantID)

if err != nil {
    fmt.Printf("NewOAuthConfig fail %v", err.Error())
}

oauthClient := &autorest.Client{}
fmt.Println("oauthClient: \n", oauthClient)
deviceCode, err := adal.InitiateDeviceAuth(oauthClient, *oauthConfig, dfc.ClientID, dfc.Resource)
if err != nil {
    fmt.Printf("Init Auth fail %v", err.Error())
}
fmt.Println("%v", *deviceCode.Message)
token, err := adal.WaitForUserCompletion(oauthClient, deviceCode)
if err != nil {
    fmt.Println("failed to finish device auth flow: ", err)
}
```

**Comment by jhendrixMSFT** [comment]
In `adal.CheckForUserCompletion()` could you try printing the raw response body to the console and post it here?

**Comment by jhendrixMSFT** [comment]
We should be including the raw response body for these generic error responses.  Unfortunately there's no way to do this without introducing a breaking change.

**Comment by Devinwong** [comment]
While I am checking how to collect HTTP proxy logs, here are some findings from my vs code.
![vscode_CheckForUserCompletion](https://user-images.githubusercontent.com/13621569/59398811-237cd200-8dc4-11e9-94af-93a5e036315d.jpg)

The error description was trimmed "AADSTS7000218: The request body must contain the following param...+179 more"
So I searched it on internet and got this.
It seems that it’s related to a property PublicClient.
From the Manifest of my application, "PublicClient": false,
And in Azure CLI’s page, it’s true. But I didn’t find any place to change it.

Another two differences we found from Azure CLI and my application was that Azure CLI is Native Application but mine is Web/API Application. Also Azure CLI’s Implicit Grant is Id token but mine is access token.
![AAD1](https://user-images.githubusercontent.com/13621569/59398835-44452780-8dc4-11e9-8eb0-787b95b98e62.jpg)
![AAD2](https://user-images.githubusercontent.com/13621569/59398841-47d8ae80-8dc4-11e9-92f0-f9ae9cef2fd5.jpg)
I am requesting another application ID as Native application.

**Comment by Devinwong** [comment]
It turned out that I needed to select Native application rather than Web/API application on aad onboarding site. As this is critical for an application to get access token correctly, I think it needs to be well documented. And it will be super helpful to have a clear flow and status controlled by a good system for internal team to pass all the required steps in order to get a correct application ID with correct accesses.
