### ISSUE TITLE
should NewOAuthConfig still be used in auth.go

### ISSUE THREAD

**Issue by weinong** [Azure/go-autorest#405]
[`NewOAuthConfig`](https://github.com/Azure/go-autorest/blob/ea233b6412b0421a65dc6160e16c893364664a95/autorest/adal/config.go#L44) has an issue where the issued token's `aud` will have `spn:` prefix due to using the `1.0` api version. [`NewOAuthConfigWithAPIVersion`](https://github.com/Azure/go-autorest/blob/ea233b6412b0421a65dc6160e16c893364664a95/autorest/adal/config.go#L51) was added to solve that. Though `NewOAuthConfig` is still called in `autorest/azure/auth/auth.go`.

Should we move it to `NewOAuthConfigWithAPIVersion` in `auth.go` in favor of not using any api version?

**Comment by jhendrixMSFT** [comment]
I am loathe to change it as it's unclear if there would be any unwanted side-effects.

Let's make sure that the track 2 authentication module [azidentity](https://github.com/Azure/azure-sdk-for-go/tree/track2/sdk/azidentity) works as expected for you.
