### ISSUE TITLE
Support cap on backoff delay

### ISSUE THREAD

**Issue by yangl900** [Azure/go-autorest#409]
We use `DelayForBackoff` in many places, it does exponential back-off but with no capping.

As a service many times we want to achieve behavior like, back off start from 1s, then exponential, but at maximum, retry every 60s (cap at 60). 

this allows client get faster signal from polling. Also we don't easily get crazy hours back-off.

https://github.com/Azure/go-autorest/blob/946071b7112e0f046a01908297e5c9f446ff6ce6/autorest/sender.go#L319

**Comment by jhendrixMSFT** [comment]
Fixes in https://github.com/Azure/go-autorest/releases/tag/v12.3.0, see DelayForBackoffWithCap
