### ISSUE TITLE
Azure go-autorest causing ambiguous import

### ISSUE THREAD

**Issue by 27149chen** [Azure/go-autorest#414]
Got an ambiguous import error when run go get ./... under a go module enabled project:

```
build github.com/.../cmd/manager: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-autorest v11.2.8+incompatible (/go/pkg/mod/github.com/!azure/go-autorest@v11.2.8+incompatible/autorest)
	github.com/Azure/go-autorest/autorest v0.3.0 (/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.3.0)
```
go-autorest is introduced by client-go. 
here is the line in my go.mod:
```
github.com/Azure/go-autorest/autorest v0.3.0 // indirect
```
but in the go.sum, there are many lines:
```
github.com/Azure/go-autorest v11.2.8+incompatible h1:Q2feRPMlcfVcqz3pF87PJzkm5lZrL+x6BDtzhODzNJM=
github.com/Azure/go-autorest v11.2.8+incompatible/go.mod h1:r+4oMnoxhatjLLJ6zxSWATqVooLgysK6ZNox3g/xq24=
github.com/Azure/go-autorest/autorest v0.3.0 h1:yOmXNB2qa2Kx40wMZB19YyafzjCHacXPk8u0neqa+M0=
github.com/Azure/go-autorest/autorest v0.3.0/go.mod h1:AKyIcETwSUFxIcs/Wnq/C+kwCtlEYGUVd7FPNb2slmg=
github.com/Azure/go-autorest/autorest/adal v0.1.0 h1:RSw/7EAullliqwkZvgIGDYZWQm1PGKXI8c4aY/87yuU=
github.com/Azure/go-autorest/autorest/adal v0.1.0/go.mod h1:MeS4XhScH55IST095THyTxElntu7WqB7pNbZo8Q5G3E=
github.com/Azure/go-autorest/autorest/date v0.1.0/go.mod h1:plvfp3oPSKwf2DNjlBjWF/7vwR+cUD/ELuzDCXwHUVA=
github.com/Azure/go-autorest/autorest/mocks v0.1.0/go.mod h1:OTyCOPRA2IgIlWxVYxBee2F5Gr4kF2zd2J5cFRaIDN0=
github.com/Azure/go-autorest/logger v0.1.0/go.mod h1:oExouG+K6PryycPJfVSxi/koC6LSNgds39diKLz7Vrc=
github.com/Azure/go-autorest/tracing v0.1.0/go.mod h1:ROEEAFwXycQw7Sn3DXNtEedEvdeRAgDr0izn4z5Ij88=
```

**Comment by jhendrixMSFT** [comment]
What's triggering the dependency on v11.2.8+incompatible?  That's the source of the problem.

**Comment by jhendrixMSFT** [comment]
You might need to use a `replace` directive in your go.mod file.  We recently added some documentation about this here https://github.com/azure/go-autorest#using-with-go-modules.  Can you try it?

**Comment by bcmills** [comment]
A `replace` directive should never be necessary. A more appropriate resolution would be to modify the nested modules to `require` a version of the parent module that removes the ambiguous package.

(See, for example, the requirement on `cloud.google.com/go` in https://code-review.googlesource.com/c/gocloud/+/43891.)

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT would it make sense to switch back to using one tag for the entire repository (as previously) - rather than doing so for individual packages, since they've all got to be used together anyway?

**Comment by jhendrixMSFT** [comment]
Not all of them need to be used together, e.g. some modules are only consumed via code generation (e.g. `validation`), so having them split up allows us to make breaking changes without impacting unrelated modules (e.g. `auth`).
It's still not clear to me where the dependency on `v11.2.8+incompatible` came from and if it can be removed; this version predates the release of modules in this repo.  @27149chen can you provide complete repro steps and a link to your source code?

**Comment by jhendrixMSFT** [comment]
@bcmills you're right, using `replace` was bad advice and I admit it stems from still not fully understanding how modules interact with pre-modules dependencies.
I'm looking at the reference you provided and read the associated wiki section.  To make sure I correctly understand, I'd want to update module `./autorest/validation` to have a dependency on its parent module `./autorest`, and apply this same logic to all sub-modules.  Going forward does that mean that every time a parent module has a minor/patch update all of its sub-modules must be updated to require the new version?  Can this "fake" requirement ever be removed (perhaps in v2+)?

**Comment by bcmills** [comment]
> Going forward does that mean that every time a parent module has a minor/patch update all of its sub-modules must be updated to require the new version?

Nope. They only need to refer to _some_ version of the parent module that doesn't contain conflicting package definitions. (They only need to upgrade beyond that if they actually use packages from the parent module, which does not seem to be the case here.)

**Comment by bcmills** [comment]
> Can this "fake" requirement ever be removed (perhaps in v2+)?

If we address https://github.com/golang/go/issues/27899, then you can remove the fake requirement when you drop support for versions of the `go` command that do not include the fix.

**Comment by jhendrixMSFT** [comment]
Awesome thanks for the feedback, will work on this today.

**Comment by jhendrixMSFT** [comment]
For module `./tracing/opencensus` I believe the workaround is not required since it wasn't "carved out from its parent module (was added later), correct?

**Comment by jhendrixMSFT** [comment]
Another question, this repo  has no `go.mod` in its root as it seemed unnecessary given that it would contain no content.  Is this ok or do I need to add a root `go.mod` associated with a root version (e.g. v13.1.0) so I can carve out everything underneath it?

**Comment by bcmills** [comment]
> For module `./tracing/opencensus` I believe the workaround is not required since it wasn't "carved out" from its parent module (was added later), correct?

That sounds right. You only need the reverse edge to remove ambiguous packages, so if there are no such packages to remove then you're good without it.

**Comment by bcmills** [comment]
> this repo has no `go.mod` in its root as it seemed unnecessary given that it would contain no content.

If the root is already above `v1`, then you really _do not_ want to add a `go.mod` file there. When you add a `go.mod` file you have to comply with [semantic import versioning](https://tip.golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning) (by adding a major-version suffix), and that makes it an entirely different module altogether (and thus of no use for removing the ambiguous import).

**Comment by jhendrixMSFT** [comment]
That's right, I remember having this epiphany when I originally added modules to this repo.

Unfortunately the `./autorest/adal` module is imported by its parent, so I cannot implement the workaround for it (I had debated keeping `adal` within the `autorest` module but decided against it as I wanted it to version independently).  I'm unsure how to proceed in this case, do you have any advice?

**Comment by bcmills** [comment]
The `go.mod` file is allowed to be incomplete, so you can have either (or both) of `autorest/adal` and `autorest` depend on each other, or you can provide only the dependency from `autorest/adal` on the compatible `autorest`, in which case users of `autorest` may end up adding an `indirect` requirement on `autorest/adal` in their own module.

**Comment by jhendrixMSFT** [comment]
Hmm maybe I'm misunderstanding something here.  I'm using https://code-review.googlesource.com/c/gocloud/+/43891 as a template and added a blank import on `github.com/Azure/go-autorest/autorest` from new file `./autorest/adal/workaround.go` however when I `go build` I receive the following error.
```
can't load package: import cycle not allowed
package github.com/Azure/go-autorest/autorest/adal
        imports github.com/Azure/go-autorest/autorest
        imports github.com/Azure/go-autorest/autorest/adal
```

**Comment by bcmills** [comment]
Did you remember to valve off the new file with a `+build` constraint? You want it to be visible to `go mod tidy` (which mostly ignores constraints) but not to `go build`.

**Comment by jhendrixMSFT** [comment]
Ah no I totally missed that, it's working now.  Thanks a bunch for your help :).

**Comment by jhendrixMSFT** [comment]
This should now be resolved with the latest module versions.  @27149chen please let me know if you continue to have problems.

**Comment by BruceWangNo1** [comment]
To anyone who is struggling with this issue, I managed to avoid this problem by removing the following two lines in go.mod.

```text
github.com/Azure/go-autorest/autorest v0.9.2 // indirect
github.com/Azure/go-autorest/autorest/to v0.3.0 // indirect
```

```bash
go mod tidy
```

Something is wrong with v0.3.0, I suppose.
Reference: https://github.com/kubernetes/client-go/issues/628

**Comment by lryong** [comment]
Has this problem been solved, I also encountered this problem and did not find a solution
