### ISSUE TITLE
make DefaultPollingDelay non-const

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/go-autorest#42]
autorest/client.go:
> ![image](https://cloud.githubusercontent.com/assets/159209/13543575/55693530-e221-11e5-9114-3321bff66fa1.png)

Some RPs (for some endpoints) drop the Retry-After header and they actually return an `Azure-AsyncOperation`  header even though the operation was completed (response body actually has field `"provisioningStatus": "succeeded"`).

Just because they return the header anyway and omit `Retry-After` we wait full 60 seconds doing nothing. This especially impacts docker-machine user experience and puts us behind. During a `docker-machine` creation, we wait full 60 seconds about 3-4 times (so losing 3-4 minutes for nothing). I'd love to set this to 10 or 15 seconds if it was possible.

@brendandixon is it ok to make  this field a `var`, not a `const`?

**Comment by brendandixon** [comment]
@ahmetalpbalkan Sure. I suggest we make it a variable on autorest.Client. Then it can be tuned easily. Ok?

**Comment by ahmetalpbalkan** [comment]
Works for me. Does the entire Azure SDK use one instance of autorest.Client or is it per pkg/client?

**Comment by brendandixon** [comment]
@ahmetalpbalkan No. It uses a single instance of autorest.Client per package (e.g., arm/compute, arm/storage). This enables emitting a per-package UserAgent string. Unless I did some interesting refactoring, you would need set the timeout values once for each package client created.

**Comment by ahmetalpbalkan** [comment]
@brendandixon I think it'll be useful to let users set a "default HTTP client factory" on this centralized factory object we're planning to come up with. Setting autorest.Client per client is too tedious and having a http.Client factory would be useful and clients can still set UA string.

**Comment by brendandixon** [comment]
@ahmetalpbalkan I feel strongly that the UserAgent must be set per-package. I also do not believe we can (or should) rely on consumers to set it correctly. These constraints limit what we can do.

We could surface the notion of shared state used to initialize an autorest.Client. I don't particularly care for this since it could be just as easily handled by passing the created client to a user-written method that sets the defaults. Such an approach adds just one line of code (beyond writing the "set defaults" method) to every location that instantiates a package client.

Generally, I am opposed to "magic" and heavily defaulted code as it tends to get quite obscure over time. I am all for ease of establishing state, on the other hand.

**Comment by ahmetalpbalkan** [comment]
> I feel strongly that the UserAgent must be set per-package. I also do not believe we can (or should) rely on consumers to set it correctly.

that's why I'm saying, we should let users to define a `func() *http.Client`  on centralized client factory, and we invoke this func, get a HTTP client and set the UA on that. As far as I know, UserAgent is not part of `net/http.Client`, it's just a header we set in the request.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Neither are the timeout values used in polling. Those are internal to autorest.Client. Enabling consumers to provide a pre-configured ```*net/http.Client``` will not address your original request. (It would ease, I suppose, creating multiple clients all relying on the same Cancel channel.)

My proposal works and, I do not believe, is not arduous for consumers. In fact, it's no more difficult than creating a factory for ```*net/http.Client``` and does not disturb the existing model (which keeps each client separate with properly unique UserAgent strings).

**Comment by brendandixon** [comment]
@ahmetalpbalkan There's no place (i.e., struct) for such a factory to live. For a user to supply a factory, they have to inform the package of its existence, which means they'd have put the "pointer" to the interface somewhere. There is no base object in the go-autorest world to which they could attach such a thing.

I still believe that, even if they were such a location, having a private method they use to prepare the Client they create is essentially equivalent work.

**Comment by ahmetalpbalkan** [comment]
I guess at this point, anything works really.
