### ISSUE TITLE
WaitForCompletionRef should handle individual status GET requests timing out

### ISSUE THREAD

**Issue by paulmey** [Azure/go-autorest#426]
In Packer, we [deploy a template and wait for it to complete](https://github.com/hashicorp/packer/blob/master/builder/azure/arm/step_deploy_template.go#L51-L54), using the [default PollingDuration of 15 minutes](https://github.com/Azure/go-autorest/blob/master/autorest/client.go#L38). Mostly this works fine, but lately we've seen cases where an individual operation status request to ARM does not return a response. Here's an example where the deployment actually succeeded, but we timed out because the third request for status timed out: (logging comes from the [Packer Azure inspector](https://github.com/hashicorp/packer/blob/master/builder/azure/arm/inspector.go))

``` log
PACKER ERR 2019/06/28 16:48:47 [INFO] Packer version: 1.4.0
<...>
PACKER ERR 2019/06/28 16:48:49 packer: 2019/06/28 16:48:49 Azure request method="PUT" request="https://management.azure.com/subscriptions/[REDACTED]/resourcegroups/IT_testtemplates_template-dnp1pfkhux0/providers/Microsoft.Resources/deployments/pkrdp0jwvdcbkl0?[REDACTED]" ...
PACKER ERR 2019/06/28 16:48:49 packer: 2019/06/28 16:48:49 Azure response body=...
PACKER ERR 2019/06/28 16:48:49 packer: 2019/06/28 16:48:49 Azure request method="GET" request=".../operationStatuses/08586398663559604069?[REDACTED]" body=""
PACKER ERR 2019/06/28 16:48:49 packer: 2019/06/28 16:48:49 Azure response request="..." x-ms-request-id="71662ad9-db86-4651-83bd-0a0c1836ae58" body="{\"status\":\"Accepted\"}" status="200 OK" method="GET"
PACKER ERR 2019/06/28 16:49:49 packer: 2019/06/28 16:49:49 Azure request method="GET" request=".../operationStatuses/08586398663559604069?[REDACTED]" body=""
PACKER ERR 2019/06/28 16:49:50 packer: 2019/06/28 16:49:50 Azure response status="200 OK" method="GET" request="..." x-ms-request-id="5abc11e0-2416-451f-a6c0-ab16170f49fe" body="{\"status\":\"Running\"}"
PACKER ERR 2019/06/28 16:50:50 packer: 2019/06/28 16:50:50 Azure request method="GET" request=".../operationStatuses/08586398663559604069?[REDACTED]" body=""
PACKER ERR 2019/06/28 17:06:51 ui error: ==> azure-arm: Future#WaitForCompletion: context has been cancelled: StatusCode=0 -- Original Error: context deadline exceeded
```

The best way to handle this would be to give each status GET request it's own deadline/timeout and retry if it times out (either by treating it as not-done, by retrying immediately or a combination?).

**Comment by jhendrixMSFT** [comment]
In https://github.com/Azure/go-autorest/pull/358 I made a change so that if the context provided to `WaitForCompletionRef()` has a deadline it will be used instead of the default 15 minute timeout.  Will this work for you?

**Comment by paulmey** [comment]
No. The problem is that one single GET request for operation status can fill up the entire timeout. The request at 16:48:49 has an immediate response (same timestamp). Same with 16:49:49, immediate response. For some reason, the request 16:50:50 never receives a response and the whole WaitForCompletionRef times out at 17:06:51. From other logs, I know that this particular operation actually succeeded around 16:50, so if we'd just timed out that one request and polled again, we would have noticed the success instead of timing out.

**Comment by jhendrixMSFT** [comment]
I have trepidations about this as it seems like a band-aid, masking the underlying problem.  Is it really some transient network problem or is this something the ARM team needs to investigate?
At any rate, if we were to implement this it would have to be opt-in.  Another (preferred) option is that `WaitForCompletionRef()` is built on public primitives, so you could roll-your-own algorithm.

**Comment by paulmey** [comment]
I agree that this is a symptom of something else being wrong and I need to do more investigation to figure out what's actually going on.

> Another (preferred) option is that WaitForCompletionRef() is built on public primitives, so you could roll-your-own algorithm.

That is a great idea! We're passing in a `autorest.Client`, so maybe I could wrap that to put timeouts on the individual requests...? I need to see if I can bubble up the timeout in a way that WFCR will actually retry.

**Comment by jhendrixMSFT** [comment]
I was thinking something like the following.  It's mostly a copy/paste of `Future.WaitForCompletionRef` but uses the background context when polling which will never be cancelled.  It still uses the retry counts from the client however you could easily make those parameters if you want to have custom values at certain call sites without having to muck with the client's values.
```go
future, _ := client.Create(context.Background(), "rg", "cache", redis.CreateParameters{})
err = WaitForCompletion(&future.Future, client.Client)
// ...
// WaitForCompletion is a custom implementation of Future.WaitForCompletion.
func WaitForCompletion(f *azure.Future, c autorest.Client) error {
	// background context will never be cancelled
	ctx := context.Background()
	done, err := f.DoneWithContext(ctx, c)
	for attempts := 0; !done; done, err = f.DoneWithContext(ctx, c) {
		if attempts >= c.RetryAttempts {
			return autorest.NewErrorWithError(err, "Future", "WaitForCompletion", f.Response(), "the number of retries has been exceeded")
		}
		// we want delayAttempt to be zero in the non-error case so
		// that DelayForBackoff doesn't perform exponential back-off
		var delayAttempt int
		var delay time.Duration
		if err == nil {
			// check for Retry-After delay, if not present use the client's polling delay
			var ok bool
			delay, ok = f.GetPollingDelay()
			if !ok {
				delay = c.PollingDelay
			}
		} else {
			// there was an error polling for status so perform exponential
			// back-off based on the number of attempts using the client's retry
			// duration.  update attempts after delayAttempt to avoid off-by-one.
			delayAttempt = attempts
			delay = c.RetryDuration
			attempts++
		}
		// wait until the delay elapses or the context is cancelled
		delayElapsed := autorest.DelayForBackoff(delay, delayAttempt, ctx.Done())
		if !delayElapsed {
			return autorest.NewErrorWithError(ctx.Err(), "mypkg", "WaitForCompletion", f.Response(), "context has been cancelled")
		}
	}
	return nil
}
```

**Comment by jhendrixMSFT** [comment]
We've implemented this in our track 2 [retry policy](https://github.com/Azure/azure-sdk-for-go/blob/master/sdk/azcore/policy_retry.go#L147) which is used when calling `PollUntilDone()` which is the track 2 equivalent of `WaitForCompletionRef()`.  Closing as we won't be fixing this in track 1.
