### ISSUE TITLE
Unable to initiate Device authentication as described in the documentation

### ISSUE THREAD

**Issue by Deepak-Babu** [Azure/go-autorest#433]
Hi Team,

I'm trying to follow the documentation provided here:  https://github.com/Azure/go-autorest/tree/master/autorest/adal 
for programming device authorization. I'm unable to instantiate deviceCode as described in the documentation.

The following is my code:
```
oauthClient := &http.Client{}
OAuthConfig, err := adal.NewOAuthConfig(LoginURL, Tenant)
deviceCode, err := adal.InitiateDeviceAuth(
				oauthClient,
				OAuthConfig,
				ClientID,
				Resource)
			if err != nil {
				fmt.Errorf("Failed to start device auth flow: %s", err)
			}
```
I get the following build error: 
```
cannot use OAuthConfig (type *adal.OAuthConfig) as type adal.OAuthConfig in argument to adal.InitiateDeviceAuth
```
While I'm new to Go Lang, I've tried a few other combinations to get this to work. I believe there is a mismatch between the output from 'adal.NewOAuthConfig' and what 'adal.InitiateDeviceAuth' expects.

Please let me know if and how this can be resolved.

Regards,
Deepak

**Comment by jhendrixMSFT** [comment]
It's a bug in the documentation, I'll get it updated.  Since `OAuthConfig` is a pointer, and `adal.InitiateDeviceAuth()` takes an `OAuthConfig` by value, you need to dereference `OAuthConfig`.

**Comment by jhendrixMSFT** [comment]
Doc has been updated.

**Comment by Deepak-Babu** [comment]
When I try as per the new documentation, I get the following runtime error:
panic: runtime error: invalid memory address or nil pointer dereference

The following is my code :
```
oauthClient := &http.Client{}

oauthConfig, err := adal.NewOAuthConfig(LoginURL, Tenant)
deviceCode, err := adal.InitiateDeviceAuth(
	oauthClient,
	*oauthConfig,
	ClientID,
	Resource)
if err != nil {
	fmt.Errorf("Failed to start device auth flow: %s", err)
}

```

**Comment by jhendrixMSFT** [comment]
Did you check if `err` is non-nil after the call to `adal.NewOAuthConfig()`?  If an error was returned then `oauthConfig` is likely nil.
