### ISSUE TITLE
Unable to initiate Device authentication as described in the documentation-- Even after Incorporating the recent changes in the documentation

### ISSUE THREAD

**Issue by Deepak-Babu** [Azure/go-autorest#434]
Hi Team,

I'm trying to follow the documentation provided here: https://github.com/Azure/go-autorest/tree/master/autorest/adal
for programming device authorization. I'm unable to instantiate deviceCode as described in the documentation.

The following is my code:
```
oauthClient := &http.Client{}

oauthConfig, err := adal.NewOAuthConfig(LoginURL, Tenant)
deviceCode, err := adal.InitiateDeviceAuth(
	oauthClient,
	*oauthConfig,
	ClientID,
	Resource)
if err != nil {
	fmt.Errorf("Failed to start device auth flow: %s", err)
}
```

I get the following runtime error:
```
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by Deepak-Babu** [comment]
The error returned from the InitiateDeviceAuth() call is as follows:
```
err
<error>
data:<*errors.errorString>(0xc0002e6030)
<errors.errorString>
s:"autorest/adal/devicetoken: Error occurred while handling respons...+52 more"
```

**Comment by jhendrixMSFT** [comment]
I can't repro this.  Can you please provide the following.

- Values for LoginURL and Resource
- Full stack where the panic happens
- Complete error message returned from InitiateDeviceAuth()

**Comment by Deepak-Babu** [comment]
This was an error in configuration. Thank you for helping with this and the earlier issue as well.
