### ISSUE TITLE
Client has refresh_token, but go-autorest returns error on refresh

### ISSUE THREAD

**Issue by Moeser** [Azure/go-autorest#435]
See downstream issue at https://github.com/hashicorp/go-azure-helpers/issues/22

The client is authenticating via cached azure cli credentials, which include the refresh token.  On refresh, after an hour or so of runtime, the following error is returned: "Manually created ServicePrincipalToken does not contain secret material to retrieve a new access token".  That error appears to be coming from the go-autorest library here:

https://github.com/Azure/go-autorest/blob/91963f35f69f165284aa0789fa1b5a726cb2cceb/autorest/adal/token.go#L173

Is this a bug in go-autorest?  Maybe that error should only be thrown if the refresh token is also not present?

Here's how the client is setting up the token:
https://github.com/hashicorp/go-azure-helpers/blob/e1c07bf7137ebb4c3ea824efa392ce8b2ecc7a63/authentication/auth_method_azure_cli_token.go#L71

**Comment by jhendrixMSFT** [comment]
Are you sure the refresh token is included?  When I run the `az` command in `obtainAuthorizationToken()` no refresh token is returned.

**Comment by Moeser** [comment]
Interesting, on double checking that az command, I don't see the refreshtoken either.  If the refreshtoken were pulled in from another source (such as reading az's accessTokens.json or something) would refreshing be successful?

**Comment by jhendrixMSFT** [comment]
As long as the grant type isn't authorization code then yes it should work.  See https://github.com/Azure/go-autorest/blob/91963f35f69f165284aa0789fa1b5a726cb2cceb/autorest/adal/token.go#L812-L823

**Comment by Moeser** [comment]
Thanks @jhendrixMSFT .  Since this isn't looking like a bug in go-autorest, I'll close this issue out.
