### ISSUE TITLE
Fix OpenCensus and OCAgent dependencies in all modules

### ISSUE THREAD

**Issue by tamalsaha** [Azure/go-autorest#438]
xref: https://github.com/Azure/go-autorest/pull/437

@jhendrixMSFT , we have a package that depends on both Azure and K8s. But `go mod` is not picking the correct version of OpenCensus and OCAgent dependencies.

Here is the not working commit:
https://github.com/gomodules/stow/commit/b5cfd0729a2e449576e8ca8ebee9be4b2e48d1e6

Working commit:
https://github.com/gomodules/stow/commit/59f23d30861229472e1e6abb5d008b6703773171

To use the old version of OpenCensus and OCAgent dependencies, we need to add them to the replace section.

So, it seems to me that all the submodules of autorest repo should also use `github.com/Azure/go-autorest/tracing v0.2.0`.

What do you think?

**Comment by jhendrixMSFT** [comment]
I believe it's not working due to this import.
```
github.com/Azure/azure-sdk-for-go v31.1.0+incompatible
```
I haven't released an updated azure-sdk-for-go that references the updated go-autorest; I plan to do that today.  Your solution seems reasonable, or you could wait until I have a patched version of the SDK (working on it now).

**Comment by tamalsaha** [comment]
Thanks! I am going to wait for the release.

**Comment by tamalsaha** [comment]
Thanks! I am going to wait for the release.

Also, please make sure that the `github.com/Azure/azure-sdk-for-go` repo does not need any replacements, because replacements are not transitively respected by go mod.

**Comment by jhendrixMSFT** [comment]
Right now `azure-sdk-for-go` doesn't define any modules so there will be no replacements in it.  There is one in the `tracing` module in `go-autorest` to pin the version of `opencensus-proto`.  Are you saying this won't be respected?

**Comment by tamalsaha** [comment]
See here:
https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

```
As described in the 'go.mod' concepts section above, replace directives provide additional control in the top-level go.mod for what is actually used to satisfy a dependency found in the Go source or go.mod files, while replace directives in modules other than the main module are ignored when building the main module.
```

**Comment by jhendrixMSFT** [comment]
You're right, thanks for pointing this out.  I'm working on an updated fix for this.

**Comment by jhendrixMSFT** [comment]
I updated the tracing module, v0.3.0, to remove the `replace` directive.  Can you check to see if this latest version resolves your issue?  Since there are no go.mod files in `azure-sdk-for-go` I don't think any update is required there.

**Comment by tamalsaha** [comment]
It does not seem to work. Look at the version for protobuf.
https://github.com/gomodules/stow/commit/c413fa8fa6640b011060956bd66b24e326ec20c1#diff-31be3fbc3cb3d1a36172f2111034b4ceR70

This library also depends on Google's client. But that has the correct version of protobuf.
https://github.com/googleapis/google-cloud-go/blob/v0.39.0/go.mod

**Comment by jhendrixMSFT** [comment]
Using `go mod graph` I realized that the `adal` and `autorest` modules still depend on the old `tracing` package, I will get this fixed.
I also noticed that module `gomodules.xyz/stow`  depends on `google.golang.org/api@v0.7.0` which also pulls in `protobuf@v1.3.1`; you'll need to change this else v1.3.1 will still be pulled in.

**Comment by tamalsaha** [comment]
Please ping me once the adal and autorest modules are updated. I am going to check again. I am going to try with google.golang.org/api@v0.5.0 next time. 
https://github.com/googleapis/google-api-go-client/blob/v0.5.0/go.mod

**Comment by jhendrixMSFT** [comment]
Modules `autorest/adal/v0.3.0` and `autorest/v0.6.0` are now available.  I cloned your repo, updated the modules included `google.golang.org/api@v0.5.0` and it worked.  You will also need to remove the indirect dependency on `contrib.go.opencensus.io/exporter/ocagent v0.4.12` from your go.mod file.

**Comment by tamalsaha** [comment]
Thanks @jhendrixMSFT ! I just tried the same thing. See this branch
https://github.com/gomodules/stow/commit/0358d06e051bcfb300014b82d51b114624b6835f

But my code **does not compile**:

```
~/g/s/g/stow (x890) $ go build -mod=vendor ./...
vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go:21:2: cannot find package "." in:
	/home/tamal/go/src/gomodules.xyz/stow/vendor/go.opencensus.io/exemplar

```

**Comment by jhendrixMSFT** [comment]
OK I have it building now with `autorest@v0.7.0` `tracing@v0.4.0` (gets removed by `go mod tidy`) and `api@v0.5.0`.  Can you please verify?

**Comment by tamalsaha** [comment]
I just tried it and I am still getting the same error.

Here is my commit: https://github.com/gomodules/stow/commit/66f453d0700b19be0a41f6640a76be2a9275c76e

The problem we are seeing here is this:

The first version where census-ecosystem/opencensus-go-exporter-ocagent removed the exemplar package also added dependency on protobuf 1.3.0. 

See here: https://github.com/census-instrumentation/opencensus-go/pull/1124

https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/53 was merged on March 19, 2019 and was part of https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/releases/tag/v0.4.8 . But this release also needs protobuf 1.3.0. 

So, the latest version census-ecosystem/opencensus-go-exporter-ocagent we can take is v0.4.7 .

Also, we need a version of go.opencensus.io that was released before Apr 22, 2019. The latest such release is https://github.com/census-instrumentation/opencensus-go/releases/tag/v0.20.2.

Will go-autorest work with these versions?

**Comment by tamalsaha** [comment]
Unless you can think of anything else to do, I am going to go with `cloud.google.com/go@v0.34.0`. Until k8s switches to protobuf 1.3.x, I don't see a good solution. Feel free to close this issue.

Thank you for all your help.

**Comment by jhendrixMSFT** [comment]
I agree with you that adding these dependencies on opencensus was a mistake, it has also caused problems for the kubernetes folks when trying to update to later versions of the SDK/go-autorest.
If you have a working solution that's awesome, sorry for the trouble this has caused.  I'm debating removing these dependencies, stubbing out tracing support so callers can plug in whatever tracing package they want.

**Comment by tamalsaha** [comment]
The good news is opencensus is dead. New kid on the block is  https://opentelemetry.io/ . :face_with_head_bandage:

**Comment by jhendrixMSFT** [comment]
ok I believe this has finally been resolved.  the dependencies on opencensus have been moved to the `opencensus` package which is not included by default (see the CHANGELOG for details).
