### ISSUE TITLE
Including this dependency indirectly pull opencensus.io that breaks the build

### ISSUE THREAD

**Issue by khowling** [Azure/go-autorest#448]
Hi,

I'm trying to update the `external_dns` project, I've needed to update the Azure Go SDK import string (format has changed), but I'm not touching the `go-autorest` , so its now importing 
```
	"github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/"
	"github.com/Azure/go-autorest/autorest"
```

But now I cannot get it to build, as it always now seams to be indirectly adding the following modules: (content of `go.mod`)
```
github.com/Azure/azure-sdk-for-go v32.3.0+incompatible
github.com/Azure/go-autorest/tracing v0.4.0 // indirect
```

And in turn (content of `go.sum`):
```
contrib.go.opencensus.io/exporter/ocagent v0.4.6
```

So running `make` i get 
```
go/pkg/mod/contrib.go.opencensus.io/exporter/ocagent@v0.4.6/transform_stats_to_metrics.go:210:61: cannot use data.ExemplarsPerBucket (type []*metricdata.Exemplar) as type []*exemplar.Exemplar in argument to bucketsToProtoBuckets
```

I've tried to follow all the issues relating to this, tried adding the `replace`, I'd like to get unblocked, and if possible,  I'd like to not have to include the opencensus library.  Any help gratefully received

**Comment by jhendrixMSFT** [comment]
This has been resolved in `tracing/v0.5.0` and other modules in `go-autorest`.  Please move to the latest version(s) and the dependencies on opencensus will go away.
