### ISSUE TITLE
opencensus dependency issue with Go 1.13

### ISSUE THREAD

**Issue by vcabbage** [Azure/go-autorest#449]
When using this library with Go 1.13 (currently in beta), the following error is presented:

```
go: github.com/Azure/go-autorest/autorest@v0.8.0 requires
        github.com/Azure/go-autorest/tracing@v0.4.0 requires
        contrib.go.opencensus.io/exporter/ocagent@v0.4.6 requires
        github.com/census-instrumentation/opencensus-proto@v0.1.0-0.20181214143942-ba49f56771b8: invalid pseudo-version: version before v0.1.0 would have negative patch number
```

The pseudo-version referenced in `contrib.go.opencensus.io/exporter/ocagent@v0.4.6`'s `go.mod` is considered invalid, but Go 1.12 and earlier don't check for it.

`contrib.go.opencensus.io/exporter/ocagent` v0.4.7 does reference a valid version for `github.com/census-instrumentation/opencensus-proto`.

If the dependency has already been cached by Go 1.12 the error doesn't present itself. To reproduce you can clear your module cache or use the `golang:1.13beta1` docker container.

```
docker run -it --rm golang:1.13beta1
mkdir /test && cd /test && go mod init test
cat << EOF > main.go
package main

import _ "github.com/Azure/go-autorest/autorest"

func main() {}
EOF
go run .
```

I'm currently working around this by using a `replace`:
```
replace contrib.go.opencensus.io/exporter/ocagent => contrib.go.opencensus.io/exporter/ocagent v0.4.7
```

**Comment by vcabbage** [comment]
A more conservative `replace` would be:

```
replace github.com/census-instrumentation/opencensus-proto v0.1.0-0.20181214143942-ba49f56771b8 => github.com/census-instrumentation/opencensus-proto v0.0.3-0.20181214143942-ba49f56771b8
```

Which only fixes up the specific incorrect pseudo-version instead of upgrading a dependency.

**Comment by bcmills** [comment]
Note that you could achieve an effect equivalent to the `ocagent` upgrade more robustly with:

```
require contrib.go.opencensus.io/exporter/ocagent v0.4.7

replace github.com/census-instrumentation/opencensus-proto v0.1.0-0.20181214143942-ba49f56771b8 => github.com/census-instrumentation/opencensus-proto v0.0.3-0.20181214143942-ba49f56771b8
```

That way, your build won't break if some future `go get` or `import` adds a (transitive) dependency on a feature added in `ocagent` `v0.5.0` or later.

**Comment by jhendrixMSFT** [comment]
The dependencies on the various opencensus modules have been moved to the `opencensus` module which is not included by default, making it pay-for-play (see CHANGELOG for details).  If you don't need/want these opencensus dependencies can you please move the latest version of the autorest module (and any others you're consuming from this repo)?

**Comment by vcabbage** [comment]
@jhendrixMSFT Thank you! (btw, there's a small typo in CHANGELOG, should be `import` instead of `include`.)

**Comment by jhendrixMSFT** [comment]
Oops I'll fix that in my next change.  This should now be fixed, please let me know if you have further problems.
