### ISSUE TITLE
Provide a sharedkey authorizer

### ISSUE THREAD

**Issue by kahing** [Azure/go-autorest#456]
azure-storage-blob-go provides a `SharedKeyCredentials`. It'd be good to have an `Authorizer` version of this so we can use it in azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
I think this is will be addressed in https://github.com/Azure/go-autorest/pull/416, will work on wrapping up that review next week.

**Comment by jhendrixMSFT** [comment]
This has been added in v13.3.0.
