### ISSUE TITLE
Improve support for mocking futures and pageable operations

### ISSUE THREAD

**Issue by alexeldeib** [Azure/go-autorest#469]
The futures currently expose the polling method and URL, but reconstructing a future or otherwise using some of the utility functions is difficult due to the structure of the package and the constructor. 

What I'd like to be able to do is take a future and instead of calling `WaitForCompletionRef`, I want to extract some minimal data (pollingMethod, URL presumably), store that, and later do something like `NewFutureFromURL(URL, method)` (ignoring the naming).

I want to do this so that instead of blocking on `WaitForCompletionRef` I can call `DoneWithContext` and handle waiting/requeuing on a more granular basis myself.

The reason I do not want to use `WaitForCompletionRef` is that I am running in the context of a Kubernetes custom controller. I'd like to spawn as few workers as possible to deal with a potentially large number of resources in my workqueue, and calling this is a blocking operation for potentially long-provisioning resources. This will lead to blocking reconciliation of other objects in my work queue. I would much prefer to check the status of the operation, persist some polling metadata, and re-check the status at a later time I control.

This is also why I can't store the entire future -- persisting the future (and/or the full http response) across reconciliation runs is prohibitive. At the same time, I'd like to be as true as possible to the ARM API without reimplementing a large portion of that particular package.

thoughts?

**Comment by jhendrixMSFT** [comment]
The inner workings of `WaitForCompletionRef()` is built on public surface area of the `Future` type to allow consumers to build their own polling loop.  Please take a look and let me know if the available APIs will work for you.
In addition, futures support marshalling/unmarshalling (JSON format) so you could marshal the future into a byte slice for storage, then unmarshal it back into its concrete type when you're ready to check the status.

**Comment by alexeldeib** [comment]
I opened this issue after my experience trying to do the first. I'm trying to work up an example of the behavior i'd like, it's taking some time though.

The second option is actually okay, but I'd like to avoid persisting the full HTTP response (embedded in the tracker) to the database on every function invocation. From what I can tell, the futures only use a very limited set of fields from the full response -- mostly the original request method, to know what polling behavior is correct. 

I'd really like to be able to e.g. get a response back from an initial request using the SDK, call something like `CheckInitialResponse()`, and store a handful of fields which would let me poll again in the future to `CheckStatus()` or something like that. This behavior is difficult to implement on top of the current Future API without marshaling/unmarshaling the full HTTP response as you pointed out and storing it, but the current API could be implemented on top of that functionality. 

The issue really boils down to the fact that, if I call a `CreateOrUpdate` or other LRO, and then exit that function context, it's very difficult for me to reconstruct the status of that operation and track it from other places without persisting a pretty sizable number of bytes somewhere. I can use the resources API to try and get a list of ARM operations on that resources, I can list activity history, etc, but really I just want to store minimal metadata from the original request and track it again in the future.

**Comment by jhendrixMSFT** [comment]
Looking at the code, marshalling the future doesn't persist the entire HTTP response, just the state necessary to recreate it and start polling.  If you are seeing this happen it's a bug.

**Comment by alexeldeib** [comment]
Played around with this a bit more. Marshaling/Unmarshaling works perfectly, you're right. It'd be nice if the polling tracker struct/fields were public so I can (re)use them properly instead of embedding a byte array, but now I'm nit picking 🙂

Thanks for a great library!

**Comment by jhendrixMSFT** [comment]
This came up in a recent issue regarding mocking, i.e. it's difficult to mock an API that returns a future since you can't directly construct one.  If you'd like to see this functionality added we can recycle this issue to track it.

**Comment by alexeldeib** [comment]
That would be really useful. I've ended up e2e testing or else wrapping the behavior under a client facade that's easier to mock.

cc @frodopwns

**Comment by sopatwar** [comment]
@jhendrixMSFT thanks for referencing the mock issue here.

**Comment by CecileRobertMichon** [comment]
+1 
I'm trying to mock `Delete`/`CreateOrUpdate` functions and I'm running this exact issue https://github.com/Azure/azure-sdk-for-go/issues/409#issuecomment-538586232.  For example, I'm not able to mock `VirtualMachinesClientAPI` (`github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/computeapi`). 

The only way I found to go around this would be to create a new interface and put the CreateOrUpdate + wait for future completion functionality inside its own function so I can then mock that interface, but that would require significant refactoring and I wouldn't be able to mock the Azure compute/network APIs directly.

**Comment by devigned** [comment]
@jhendrixMSFT is mocking / testability going to be addressed with next version of the Golang SDKs?

**Comment by alexeldeib** [comment]
Given that Future is a struct type which no exported fields and a fairly small method set, turning Future into an interface, while breaking, doesn't seem awful. Perhaps we could have an exported field on the base client which is `func(...stuff) Future` (i.e., constructor for a Future) and we could mock the constructor on the client? Similar to how the SDK already treats Senders, Inspectors, etc.

Something like this: 
https://github.com/kubernetes-sigs/controller-runtime/blob/efbeb2728794b105247bbf27c76a5c4949a73010/pkg/manager/manager.go#L177-L184

https://github.com/kubernetes-sigs/controller-runtime/blob/efbeb2728794b105247bbf27c76a5c4949a73010/pkg/manager/manager.go#L362-L370

https://github.com/kubernetes-sigs/controller-runtime/blob/efbeb2728794b105247bbf27c76a5c4949a73010/pkg/manager/manager.go#L244-L248

**Comment by alexeldeib** [comment]
Illustrative examples of the sub-optimal workaround Cecile described, for reference:

Wrapper client which waits for completion: https://github.com/CecileRobertMichon/cluster-api-provider-azure/blob/cf66ed1ffffc6e09cf4ac019984839650071a76a/cloud/services/virtualmachines/client.go#L61-L72

Wrapper client which simulates async behavior and polls the future itself: 
https://github.com/alexeldeib/incendiary-iguana/blob/b43ee7a2e32378eb6ed49e4b49a08a8dac992e9f/pkg/services/group.go#L46-L88

**Comment by jhendrixMSFT** [comment]
@devigned yeah we explicitly call this out in the design guidelines for track 2.

As to a solution, for the APIs that return a future I think we can have the mock interfaces return an interface; i.e. the real APIs still return a struct but the mock interfaces return an interface (GCP does the same thing).  I haven't had a chance to prototype this to see if it has any holes though.

**Comment by jhendrixMSFT** [comment]
Here's the implementation for track 2.

VM client [BeginCreateOrUpdate](https://github.com/Azure/azure-sdk-for-go/blob/track2/sdk/arm/compute/2019-12-01/armcompute/virtualmachines.go#L32) returns a [VirtualMachinePollerResponse](https://github.com/Azure/azure-sdk-for-go/blob/track2/sdk/arm/compute/2019-12-01/armcompute/models.go#L3988).  This type exposes a `PollUntilDone()` func that can be user-defined for mocking as well as a [VirtualMachinePoller](https://github.com/Azure/azure-sdk-for-go/blob/track2/sdk/arm/compute/2019-12-01/armcompute/pollers.go#L1937) interface if you need to mock the individual async polling methods.  Any feedback on the new design is welcome, please feel free to open an issue in the SDK repo an add the `track 2` label.

Given that we won't be changing this for track 1 I'm closing this issue.
