### ISSUE TITLE
Install for azure-sdk-for-go fails

### ISSUE THREAD

**Issue by rmasci** [Azure/go-autorest#47]
many of the packages that are for azure-sdk-for-go fail because it's trying to send 2 arguments to a func that receives only one. 

Azure/azure-sdk-for-go/arm/network/applicationgateways.go:103: too many arguments in call to azure.DoPollForAsynchronous

applicationgateways.go: 103:
azure.DoPollForAsynchronous(autorest.DefaultPollingDuration,
                        autorest.DefaultPollingDelay))

async.go:
func DoPollForAsynchronous(delay time.Duration) autorest.SendDecorator {

**Comment by ahmetalpbalkan** [comment]
@rmasci  we develop the go-autorest and azure-sdk-for-go projects independently, therefore using tip of master branch from these projects are not necessarily going to be compatible. As our README.md highlights:

> NOTE: This repository is under heavy ongoing development and is likely to break over time. We currently do not have any releases yet. If you are planning to use the repository, please consider vendoring the packages in your project and update them when a stable tag is out.

You can find what version of `go-autorest` that works with the current version of azure-sdk-for-go in the `glide.lock` file in azure-sdk-for-go repo. In a nutshell, if you're using Azure SDK for Go, we strongly recommend hosting your dependencies locally in your project.

That should fix your problem. If not, please let us know. Closing for now.
