### ISSUE TITLE
Versioning of Go-AutoRest

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/go-autorest#481]
👋🏻

As a consumer of this repository (via both [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) and [Giovanni](https://github.com/tombuildsstuff/giovanni)) whilst I can understand the desire to version each package in this repository independently I think it's causing more complexity than it's solving since there's dependencies between packages.

From our side we've lost a substantial amount of time (days) over the past few months trying to diagnose versioning issues with go-autorest and the Azure SDK for Go. Ultimately we've had to roll back to using an older version of the Azure SDK for Go / go-autorest, since switching to the versioning per package breaks vendoring Terraform Core into downstream codebases, unless the downstream codebases also include a `replace` statement in their `go.mod` files - which unfortunately isn't a viable solution for us.

My concern is that these issues will be exacerbated when the Azure SDK for Go moves to a Go Module per Service Package (e.g. `./services/foobar/mgmt/2019-01-01`); where different service packages/modules depend on different versions of this package.

Given these issues are caused by there being two different tagging approaches in this repository (which can't be removed at this point since they'll be cached via the Go Module Cache) - I'm wondering if it'd be worth taking a different approach instead.

Since this library depends on itself, I believe that versioning per package may be causing more issues than it's solving. In particular whilst I understand grouping everything into a single module means the SemVer for this library may need to be bumped ([which @jhendrixMSFT previously outlined here](https://github.com/Azure/go-autorest/issues/414#issuecomment-522063283)) I'm wondering if bumping the major version is a concern for this library in practice?

Given the problems above, I'm wondering if it'd be worth essentially duplicating this repository (preferably with, but it might be less hassle without the history) but in either case without the existing tags. This'd allow this repository to be versioned starting from (say) 1.0 but critically as single unit (in the root).

There's two affects on this on downstream consumers; downstream SDK's, such as:

* [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go)
* [Giovanni](https://github.com/tombuildsstuff/giovanni)
* [hashicorp/go-azure-helpers](https://github.com/hashicorp/go-azure-helpers)
* (others)

which (technically) would require a major version bump.

Software proudcts on the other hand would only require a patch release, including:

* Kubernetes
* Prometheius
* Terraform Core & downstream Providers that vendor it
* (others)

To ease the transition for slower moving dependencies it could be beneficial to use Type Aliases in this repository to the types in the new repository (in the same way Profiles do in the Azure SDK for Go), but I don't think that's a blocker (and if it is it's easy enough to retroactively add it).

---

Whilst I appreciate this is a big ask/change - since the versioning issues has affected multiple downstream projects (including [Terraform](https://github.com/hashicorp/terraform/pull/22532) and Kubernetes which in turn has affected both [CoreDNS](https://github.com/coredns/coredns/pull/3258) and [Rancher](https://github.com/rancher/rio/pull/451) (and I believe Prometheus too, albeit I can't find the link now?)) - I'm wondering if splitting this out into it's own repository provides the simplest path forward.

Thoughts?

**Comment by alexruf** [comment]
The versioning of some Azure SDKs for Go seems to be really broken. Since `go-autorest` uses the same import path for all major versions, this leads to problems with transitive dependencies which (as far as I know) cannot be solved and therefore lead to applications not being able to compile.

e.g. code that imports `azure-sdk-for-go` and `azure-event-hubs-go`:

```golang
package main

import (
	"context"
	"fmt"
	"github.com/Azure/azure-event-hubs-go/v2"
	"github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2016-10-01/keyvault"
)

func main() {
	vaultsClient := keyvault.New("SubscriptionID")
	fmt.Printf(vaultsClient.BaseURI)

	//...

	connStr := "Endpoint=sb://namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=superSecret1234=;EntityPath=hubName"
	hub, _ := eventhub.NewHubFromConnectionString(connStr)
	hub.Close(context.Background())
}
```

I really don't know how this version conflict could be solved as long as all major versions use the same import path.

**Comment by jhendrixMSFT** [comment]
I want to apologize upfront for the headaches this has caused.  If I had to do it over again I wouldn't have rolled out modules in this repo so soon (the SDK was supposed to get modules shortly after).

I agree that the repo's inter-dependencies have made the situation complex, I underestimated this.  My thinking was to separate the packages used by the code generator (e.g. `validation` package) so that we could have the liberty of introducing breaking changes in codegen without worrying about the impact to the rest of the codebase.  While I still think there's value in this, the current implementation is too complex.

Before we go the route of moving the repo and all the fall-out that entails, I think we can remove the majority of extra modules so the problem goes away.  See [here](https://github.com/golang/go/wiki/Modules#is-it-possible-to-remove-a-module-from-a-multi-module-repository) for details on the approach.  I'm not sure what modules we'd end up with, but off-the-cuff I think the plan would be to include all package hierarchies that have inter-repo dependencies in the same module (i.e. most everything under ./autorest would become one big module).  My fear is that this would somehow make matters worse which is definitely something I don't want to do, so it's gonna take some planning and testing.  Thoughts on this?

**Comment by alexruf** [comment]
I understand that this problem has grown historically, and only came to light with the introduction of Go Modules.

Anyways, Go Modules is very opinionated about the way [import versioning](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) should work. They suggest that every major version with breaking changes must include the version at the end of the import path in the `go.mod` file (e.g., `module github.com/my/mod/v2`, `require github.com/my/mod/v2 v2.0.1` and so on) .

**Comment by jhendrixMSFT** [comment]
After reading through some of the linked issues I'm no longer convinced that reducing the number of modules (and eliminating the inter-dependencies) will solve the underlying issue at present (although it will help reduce the needless complexity).

**Comment by alexruf** [comment]
Agree, the problem here is not about the complexity. It's the dependencies and incompatibility between different versions of Go modules.

Here is a diagram to illustrate the problem even better:

```
              ┌───────────────────────────────────────┐      ┌────────────────────────────┐
              │ github.com/Azure/azure-event-hubs-go  │      │github.com/Azure/go-autorest│
          ┌──▶│                v1.3.1                 │──X──▶│          v11.1.1           │
          │   └───────────────────────────────────────┘      └────────────────────────────┘
          │
          │   ┌───────────────────────────────────────┐      ┌────────────────────────────┐
┌──────┐  │   │github.com/Azure/azure-event-hubs-go/v2│      │github.com/Azure/go-autorest│
│Go app│──┼──▶│                v2.0.4                 │──X──▶│          v12.0.0           │
└──────┘  │   └───────────────────────────────────────┘      └────────────────────────────┘
          │
          │   ┌─────────────────────────────────┐            ┌────────────────────────────┐
          │   │github.com/Azure/azure-sdk-for-go│            │github.com/Azure/go-autorest│
          └──▶│             v36.0.0             │────────X──▶│           v0.9.2           │
              └─────────────────────────────────┘            └────────────────────────────┘
```

I guess normally you could use `replace github.com/Azure/go-autorest => github.com/Azure/go-autorest v12.0.0`in your `go.mod` file to solve this kind of problems. But since those versions are incompatible among each other, it won't compile the application at the end.

**Comment by jhendrixMSFT** [comment]
Sorry for the delay on this.

Regarding the SDK, our current POR is to release each service/API version tuple as its own module (compute/2015-06-15/compute, compute/2016-03-30/compute, etc).  While I realize this seems like a lot of modules it provides the best insulation against breaking changes having inadvertent impact across API versions.

In addition, I've released a v3 of event hubs (for a different reason) that will address the above build issue.

**Comment by johanbrandhorst** [comment]
> ```
> build azure-demo: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
>	github.com/Azure/go-autorest v12.0.0+incompatible (/Users/USER/go/pkg/mod/github.com/!azure/go-autorest@v12.0.0+incompatible/autorest)
>	github.com/Azure/go-autorest/autorest v0.9.2 (/Users/USER/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.2)

Is there a workaround for this error?

**Comment by tv42** [comment]
```
$ go get github.com/Azure/go-autorest@latest
$ go get github.com/Azure/go-autorest/autorest/adal@latest
```

That's broken again. `@latest` picked up

```
        github.com/Azure/go-autorest/autorest v0.10.0 // indirect
        github.com/Azure/go-autorest/autorest/adal v0.8.3 // indirect
```

and the *second* `go mod tidy` run complains about ambiguous import. Same thing with `@master`.

**Comment by jhendrixMSFT** [comment]
@tv42 what module(s) is pulling in the dependency on `go-autorest@v12.0.0+incompatible`, presumably it's something from `azure-sdk-for-go` correct?

**Comment by tv42** [comment]
@jhendrixMSFT 

```
$ go mod why -m github.com/Azure/go-autorest
# github.com/Azure/go-autorest
(my thing that just imports gocloud.dev blob drivers)
gocloud.dev/blob/azureblob
gocloud.dev/blob/azureblob.test
github.com/Azure/go-autorest/autorest/azure/auth
```

```
$ go list -m gocloud.dev
gocloud.dev v0.19.0
```

```
$ grep go-autorest ~/go/pkg/mod/gocloud.dev@v0.19.0/go.mod
	github.com/Azure/go-autorest v12.0.0+incompatible
```

**Comment by AdamSLevy** [comment]
Solving this issue can be dramatically simplified by simply removing the current go.mod files and replacing them with a single go.mod file at the root. Finally bump a major version, add a tag, and append /vXX to the end of the module import path within the go.mod. 

Going forward simply version the entire set of packages together. Push anything you want to master, but when you tag a new release make it a major release if it has any exported API breaking changes. If you want to shield certain packages from this versioning requirement, put the packages in an `internal/` directory, which will prevent them from being imported by any packages outside of this repo.

Anything short of the above is only going to cause issues down the road for consumers of this package.

**Comment by dewey** [comment]
I am having the exact same issue as @tv42, thought I fixed it but on running `go mod tidy` a second time it's broken again.

```
my-module|feature/update-go-1.14 ⇒ go get github.com/Azure/go-autorest@latest
go: github.com/Azure/go-autorest latest => v14.1.1+incompatible
my-module|feature/update-go-1.14⚡ ⇒ go get github.com/Azure/go-autorest/autorest/adal@latest
my-module|feature/update-go-1.14⚡ ⇒ go mod tidy
my-module|feature/update-go-1.14 ⇒ go mod tidy
example.com/my-module/some-package imports
	gocloud.dev/blob/s3blob tested by
	gocloud.dev/blob/s3blob.test imports
	gocloud.dev/internal/testing/setup imports
	github.com/Azure/azure-storage-blob-go/azblob tested by
	github.com/Azure/azure-storage-blob-go/azblob.test imports
	github.com/Azure/go-autorest/autorest/adal: ambiguous import: found package github.com/Azure/go-autorest/autorest/adal in multiple modules:
	github.com/Azure/go-autorest v12.0.0+incompatible (/Users/user/go/pkg/mod/github.com/!azure/go-autorest@v12.0.0+incompatible/autorest/adal)
	github.com/Azure/go-autorest/autorest/adal v0.8.3 (/Users/user/go/pkg/mod/github.com/!azure/go-autorest/autorest/adal@v0.8.3)
```

**Comment by jhendrixMSFT** [comment]
@dewey thanks for the info.  I feel like this is the problematic line.

```
go get github.com/Azure/go-autorest@latest
```

As there is no repo-level module for go-autorest, this picks up `v14.1.1+incompatible`, clearly we want to avoid including this.

What content are you using from `go-autorest`, is it just the `adal` package?

**Comment by dewey** [comment]
I'm just using it through the following dependencies. So these are the ones importing it.

```
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"gocloud.dev/blob/s3blob"
```

**Comment by jhendrixMSFT** [comment]
Thanks I can repro this issue.  I believe this is due to the following issue.

https://github.com/Azure/azure-storage-blob-go/issues/173

I will work with the storage team to get this resolved.

**Comment by jhendrixMSFT** [comment]
This should now be resolved.  Big kudos to @miquella for digging in to understand the issue and putting together the PRs to fix it.  If anybody continues to experience version problems please let me know.

**Comment by dewey** [comment]
@jhendrixMSFT It's working for me now! Thanks for following up and thanks for putting in the work @miquella!

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff would love to get your ack that ambiguous import errors have gone away when you have a chance to try it.

**Comment by sonujose** [comment]
@jhendrixMSFT 

I am facing similar issue with keyvault sdk for go modules. 

```
	"github.com/Azure/azure-sdk-for-go/services/keyvault/2015-06-01/keyvault"
	kvauth "github.com/Azure/azure-sdk-for-go/services/keyvault/auth"
	"github.com/Azure/go-autorest/autorest"
```

Building the module throwing the following error.
```
# github.com/Azure/azure-sdk-for-go/services/keyvault/2016-10-01/keyvault
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:119:2: not enough arguments to return
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:119:15: client.Send undefined (type BaseClient has no field or method Send)
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:198:2: not enough arguments to return
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:198:15: client.Send undefined (type BaseClient has no field or method Send)
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:293:2: not enough arguments to return
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:293:15: client.Send undefined (type BaseClient has no field or method Send)
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:381:2: not enough arguments to return
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:381:15: client.Send undefined (type BaseClient has no field or method Send)
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:474:2: not enough arguments to return
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:474:15: client.Send undefined (type BaseClient has no field or method Send)
/home/sonujose/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v44.2.0+incompatible/services/keyvault/2016-10-01/keyvault/client.go:474:2: too many errors
```

**Comment by jhendrixMSFT** [comment]
@sonujose your version of the autorest module is too old.  Can you please update it?

**Comment by sonujose** [comment]
Thanks @jhendrixMSFT  Updating autorest version worked. Thanks

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT we're still using a fork of go-autorest (since we're blocked on a couple of PR's) - so that's not so easy to test right now, unfortunately

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff sorry for the delay on the PRs.  I've cleaned up and merged the fixes for shared key and SAS tokens (tagged as autorest/v0.11.3).  There is one remaining issue about a panic however we need more info.

Also, bumping go-autorest modules to their latest versions I was able to build giovanni without the need for replace directives in go.mod.  I submitted a PR [here](https://github.com/tombuildsstuff/giovanni/pull/34).  This includes the above fixes.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT thanks for that - unfortunately it appears that v45 of the Azure SDK has multiple issues which prevent us from upgrading, so whilst this appears ok (and thanks for the PR!) I can't confirm for sure until there's a version of the Azure SDK that works for us

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff glad at least part of this has been fixed.  Can you elaborate on the problems with the SDK?

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT sure, from our side there's breaking changes to the Networking package ([PR to fix](https://github.com/Azure/azure-rest-api-specs/pull/10384)) and [an issue with a discriminator](https://github.com/Azure/azure-rest-api-specs/pull/10383) which are preventing us from upgrading
