### ISSUE TITLE
Function updateErrorFromResponse doesn't reset response body stream after read it

### ISSUE THREAD

**Issue by zhedahht** [Azure/go-autorest#483]
In the code:
https://github.com/Azure/go-autorest/blob/3492b2aff5036c67228ab3c7dba3577c871db200/autorest/azure/async.go#L453

It reads data from response body stream, but doesn't reset it afterwards. Others can't read response body anymore after this function.

The function updateRawBody has similar issue:
https://github.com/Azure/go-autorest/blob/3492b2aff5036c67228ab3c7dba3577c871db200/autorest/azure/async.go#L396

Even if it has the following line to set the response body stream:
pt.resp.Body = ioutil.NopCloser(bytes.NewReader(b))

It may be bypass if the function returns earlier. A better way is to reset in defer.

**Comment by jhendrixMSFT** [comment]
Fixed in module `autorest/v0.11.12`
