### ISSUE TITLE
Azcopy login for each azcopy command

### ISSUE THREAD

**Issue by Nithin2019** [Azure/go-autorest#489]
Researchers very frustrating, as they need to run azcopy login for each azcopy command.
Adal SDK throwing:failed to refresh token, please check error details and try to log in with azcopy login command again. (Error details: Manually created ServicePrincipalToken does not contain secret material to retrieve a new access token)

We get the access/refresh tokens from the secure cache on disk, which was populated when the user invoked “azcopy login”. Btw I’m not sure why NewServicePrincipalTokenFromManualToken was picked

AzCopy is not a web application and we’re not doing MSI-based auth, don’t know how the lack of refresh source slipped out! 

We now have no refresh source and somehow have no refresh token!!

**Comment by jhendrixMSFT** [comment]
Given the lack of info and that the parent case is closed I'm closing this.
