### ISSUE TITLE
Allow Tracer to annotate span with more information like: request/response body

### ISSUE THREAD

**Issue by magodo** [Azure/go-autorest#490]
Currently only a `name` is allowed to specify at start span, then the `status code` and `err` is allowed to specify at end span.

However, it would be nice to see the request/response detail in span annotation, something like request url, request body, response body, etc.

**Comment by jhendrixMSFT** [comment]
I've added this note to the issue tracking this for track 2 codegen https://github.com/Azure/autorest.go/issues/501.  We won't be fixing this for track 1 though.
