### ISSUE TITLE
golang.org/x/crypto needs to be updated in another subfolder of go-autorest

### ISSUE THREAD

**Issue by DheerajSShetty** [Azure/go-autorest#491]
Similar to the issue https://github.com/Azure/go-autorest/issues/484
The crypto used in autorest/adal seems to be the old one still.

https://github.com/Azure/go-autorest/blob/21d4b01533b1005be0d020da67a6d3f8ebdf0141/autorest/adal/go.mod#L11

**Comment by jhendrixMSFT** [comment]
Also `./autorest/azure/auth`
