### ISSUE TITLE
Plan to add more Azure Environments?

### ISSUE THREAD

**Issue by sukhong** [Azure/go-autorest#496]
Currently, there are only 4 supported clouds in environments.go (https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go).

Is there a plan to add more Azure Environments that are coming?

This is critical for spinning up new Kubernetes clusters in new clouds, but I am wondering whether we should add new clouds into the public package or not...

**Comment by jhendrixMSFT** [comment]
Which clouds are you looking for?

**Comment by sukhong** [comment]
Had an offline discussion, and we can only add publicly available endpoints.
