### ISSUE TITLE
Add a functionality to add custom, air-gapped Azure environments (that are NOT AzureStack)

### ISSUE THREAD

**Issue by ericsuhong** [Azure/go-autorest#497]
Currently, there are only 4 hard-coded Azure environments supported: https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go.

The only way to add custom endpoints is via "hack" using AzureStackCloud.

Ideally, we would like to add custom endpoints (i.e. air-gapped environments that are not really Azure Stack) in the environments map.

The ultimate goal is to be able to add custom Azure endpoints for Kubernetes, but this will require a change in Azure Providers in Kubernetes as well.

**Comment by jhendrixMSFT** [comment]
Fixed in v14.1.0, or module autorest/v0.10.1
