### ISSUE TITLE
Add support for NewMultiTenantServicePrincipalTokenFromCertificate

### ISSUE THREAD

**Issue by yuwzho** [Azure/go-autorest#509]
I can find the only way to get token for multi-tenant SP is from client secret: https://github.com/Azure/go-autorest/blob/2368760b211997f3c5dd61e85e8665a523a09247/autorest/adal/token.go#L1108

Is there any plan to support get token from certificate as well?

**Comment by yuwzho** [comment]
@jhendrixMSFT I am sorry that I don't have a go dev environment w/ cert at hand to have a test.

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest/adal/v0.9.8` and `autorest/azure/auth/v0.5.5`
