### ISSUE TITLE
Update resourceManagerVMDNSSuffix for AzureUSGovernmentCloud

### ISSUE THREAD

**Issue by ericsuhong** [Azure/go-autorest#510]
We found out that VMDNSSuffix for AzureUSGovernmentCloud has changed to **cloudapp.usgovcloudapi.net** now:

![image](https://user-images.githubusercontent.com/3857851/75514665-dde15300-59ac-11ea-8544-dfeb4bcd59eb.png)

azure/environments.go file needs to be changed to reflect this new endpoint.

**Comment by panicstevenson** [comment]
This is also an issue for ChinaCloud: `s/cloudapp.azure.cn/cloudapp.chinacloudapi.cn/`

**Comment by jhendrixMSFT** [comment]
This has been fixed in module `autorest` v0.11.0
