### ISSUE TITLE
Error in generating auth token: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request

### ISSUE THREAD

**Issue by rudras-hub** [Azure/go-autorest#529]
Hello, 

We are unable to generate an auth token for requests when using go-autorest/adal packages. Since we were sure of the client credentials, I tried the C#  package `Microsoft.IdentityModel.Clients.ActiveDirectory` and it indeed returned a valid token. 

The error we get with go-autorest is:

error in response azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/xxx: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS700030: Invalid certificate - subject name in certificate is not authorized. SubjectNames/SubjectAlternativeNames (up to 10) in token certificate are:xxx

The go code we are using looks some thing like this:
```
func getAuthorizer(clientID string, pfxCertPath string, certPass string, tenantID string, loginAddress string, resourceAddress string) (autorest.Authorizer, error) {
	certConfig := &auth.ClientCertificateConfig{
		ClientID:            clientID,
		CertificatePath:     pfxCertPath,
		CertificatePassword: certPass,
		TenantID:            tenantID,
		AADEndpoint:         loginAddress,
		Resource:            resourceAddress,
	}

	return certConfig.Authorizer()
}
```
The authorizer returned from above is attached to an autorest generated client like this:

```
auth, err := getAuthorizer(clientID, pfxCertPath, certPass, tenantID, loginAddress, resourceAddress)
if err != nil {
    return nil, fmt.Errorf("error in getting authorizer: %v", err)
}
generatedClient.Authorizer = auth
```

The c# code that yields correct result is:
```
private static async Task<string> GetTokenHeader(string clientID, string tenantID)
{
    var pfxBytes = File.ReadAllBytes("cert.pfx");
    var cert = new X509Certificate2(pfxBytes);
    var certificateCredential = new ClientAssertionCertificate(
        clientId: clientID,
        certificate: cert);
    var uri = "https://login.microsoftonline.com/tenantID";

    var authenticationContext = new AuthenticationContext(
        authority: uri,
        validateAuthority: true,
        tokenCache: TokenCache.DefaultShared);

    var token = await authenticationContext.AcquireTokenAsync(
        resource: "https://management.azure.com/",
        clientCertificate: certificateCredential);
    
    return token.CreateAuthorizationHeader();
}
```

**Comment by rudras-hub** [comment]
Looks like the adal package makes a POST request to _https://login.microsoftonline.com/tenant-id/oauth2/token_ to obtain the token. Is the dot net library also querying the same end point while presenting the certificate? 

Base uri for the authority address is set to https://login.microsoftonline.com/ in both testscripts.

Why would the same certificate be authorized by the C# library but not by the golang library?

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.  Is this still an issue?

**Comment by rudras-hub** [comment]
Hey @jhendrixMSFT , this issue was resoled with the [commit for fixing of PFX decoding logic](https://github.com/Azure/go-autorest/commit/0529470822b50a15b3b5512b68bc2ff076e7d691). Thank you!
