### ISSUE TITLE
Add JWT Authentication Method

### ISSUE THREAD

**Issue by dgcaron** [Azure/go-autorest#537]
this is more of a question or feature request but we would like to run some commands serverside on behalf of the logged in user. In order to do so we obtain a OAuth token with the  on behalf of flow. it would be great if we could specify the obtained token so that autorest can use it to authorize the calls (instead of taking the username and password for instance).  i am willing to contribute to get this sorted if this approach would be feasible but i would need some pointers on the preffered approach and required data to get this working.

**Comment by colemickens** [comment]
I think, once upon a time, I wrote this for that sort of scenario: https://github.com/Azure/go-autorest/blob/7ac73d3561eaa034f458f97362b2743e8b3c048e/autorest/adal/token.go#L498

**Comment by dgcaron** [comment]
isn't this more for a service principal login? we actually obtain the tokens on behalf of the user (for which he consented). i'll check to see if i can give it a go with the function you provided.

**Comment by jhendrixMSFT** [comment]
We've added an authorizer that takes a JWT in `autorest/adal@v0.9.19` which I believe addresses this.
