### ISSUE TITLE
WaitForCompletionRef should respect Retry-After header returned from initial async response

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/go-autorest#538]
If an async response returns a Retry-After header, WaitForCompletionRef() should wait for the specified amount of time before starting to poll.

**Comment by tombuildsstuff** [comment]
It'd also be good to have a means of forcing/overriding this - for example where we know the interval returned from the RP is incorrect (e.g. polling every 15 seconds for for an App Service Plan inside an App Service Environment, which takes 1.5h to provision is kinda overkill)

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff presumably this is from some API call in [this](https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2019-08-01/web/appserviceenvironments.go) code?  If you have more specific details that would be helpful (e.g. specific API call) I can follow up with the App Service Environment team to see if the Retry-After value can be improved.

Short of that, your best bet would be to write a custom polling loop for services where the default implementation is sub-optimal.  I suppose we could smuggle some flags to control this via the context but I'd prefer to avoid than if possible.

**Comment by jhendrixMSFT** [comment]
Fixed in autorest/v0.11.1

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT that specific use-case is when provisioning an App Service Plan inside the ASE vs provisioning one outside of it, where it takes ~1h30m inside of an ASE and ~2m outside of one, but uses the same API endpoint/polling information.

From memory we do use a custom poller on that - arguably this should be a separate API endpoint given the behaviour is different - but there's a sufficient number of these types of these (generic) API's available throughout Azure unfortunately
