### ISSUE TITLE
move ./autorest/** to .

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/go-autorest#54]
The extra `/autorest/` segment in the go import path hierarchy does not make sense, if we do not any use case for that we should probably eventually get rid of it.

It will be a breaking change but customers must be using some vending solution by now.

**Comment by brendandixon** [comment]
@ahmetalpbalkan It is an idiom used by other Go packages. They will, as we've done here, name the repository "go-xxxxx" and then nest the package under a more meaningful name (e.g., "autorest").

We should not change. There is sufficient warrant to justify its use.

**Comment by ahmetalpbalkan** [comment]
> It is an idiom used by other Go packages. <sup>[citation needed]</sup>

**Comment by brendandixon** [comment]
@ahmetalpbalkan See:

https://godoc.org/github.com/davecgh/go-spew/spew
https://godoc.org/github.com/go-sql-driver/mysql
https://godoc.org/github.com/go-martini/martini
https://godoc.org/github.com/go-xorm/xorm
https://godoc.org/github.com/google/go-github/github
https://godoc.org/github.com/google/go-querystring/query
https://godoc.org/github.com/coreos/go-etcd/etcd
https://godoc.org/github.com/coreos/go-semver/semver
https://godoc.org/github.com/samuel/go-zookeeper/zk
https://godoc.org/github.com/garyburd/go-oauth/oauth (Gary was involved early in Go)
https://godoc.org/github.com/go-mangos/mangos
https://godoc.org/github.com/go-gorp/gorp

Shall I continue? This is just a sample of those I found searching http://godoc.org/. Next time...

**Comment by ahmetalpbalkan** [comment]
I guess that's fair enough, even though half of the go-* patterns you mentioned were just github usernames. :) it doesn't hurt to leave it like that.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Note those contributed by Google...
