### ISSUE TITLE
[feature] Make GetAuthorizer try CLI creds (or add new uber GetAuthorizer)

### ISSUE THREAD

**Issue by colemickens** [Azure/go-autorest#541]
Hi. I'd like `sops` to work better with Azure out-of-the-box by removing the user or operators need to  muck with `AZURE_AUTH_MODE`. For quick background, `sops` uses KV on-the-fly to encrpyt/decrypt secret files. Currently, they have code that handles AZURE_AUTH_MODE, but I'd rather Autorest/azure hid that entirely, if possible. 

**Suggestion 1**
Extend `GetAuthorizer` to fallback to CLI auth after trying the various envvar/cred options and after failing to hit MSI.

**Suggestion 2**
Create `GetAuthorizerExt` (please don't call it that :smile:) that does the extra fallback to CLI.

From what I was told at the time, MSI was partly to get devs to stop putting creds on their machine, and this functionality would allow tools like `sops` to even more conveniently solve the problem by automatically doing the right thing.

As-is right now, they default to `cli` authentication for `sops` (as that makes sense in the developer workflow), however, I am preparing to release something that uses `sops` and `sops-nix` on Azure with KV and I'm having to go in and manually set AZURE_AUTH_MODE="msi" to get it to work in the ideal "seamless but still secure" way.

**Comment by colemickens** [comment]
After re-checking, it looks like `sops` has its own copy of `GetAuthorizer` that (doesn't auto-try MSI but does) auto-fall back to CLI creds, so they're sort of already doing this anyway.

I'd be curious what others think, if there's value in having something in the SDK that "just works" on a devbox and in prod, but maybe it's not that important if others can already compose their own `GetAuthorizer`?

**Comment by jhendrixMSFT** [comment]
Have you seen `auth.NewAuthorizerFromEnvironment()`

https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go#L65

It will attempt to authenticate using several authentication mechanisms.  Sadly, it doesn't try CLI at present.  We could add `auth.NewAuthorizerFromCLI()` to the list of mechanisms for it to try (unclear why we didn't do this in the beginning, will look into it).  Would this work for you?

**Comment by colemickens** [comment]
Hi Joel, it would be a great solution, IMO to have another high-level single-entry point that do, as you're describing:
1. Class auth methods (env vars, client password, client secret cert, etc)
2. Then try MSI
3. Then try local CLI.

That's what I attempted to do myself, but ran into #542 and decided I don't have time to dig in quite that much... Thanks for looking!

**Comment by jhendrixMSFT** [comment]
Our solution for this in `azidentity` is the [`DefaultAzureCredential`](https://github.com/Azure/azure-sdk-for-go/blob/master/sdk/azidentity/default_azure_credential.go) which does exactly what you enumerate.

Given that you can compose this today, and that we `azidentity` is what we're moving towards, we won't be fixing this in `go-autorest`.
