### ISSUE TITLE
It is not possible to optimistically use MSI from this SDK

### ISSUE THREAD

**Issue by colemickens** [Azure/go-autorest#542]
This is related to #541 but I think warrants it's own issue.

1. Calling `msiConfig.Authorizer()` doesn't ensure you have a functioning authorizer, so you can't rely on `err=nil` to trust you have a good client. This seems like a general API issue across all auth methods.

2. One might then write extra code to call `msiConfig.ServicePrincipalToken()` *first*, ahead of time, to make sure MSI is working, *then* getting the `Authorizer()` afterward. (Or, if the call to SPT fails, go ahead and fall straight through to the trying the CLI authentication).

**First Issue**: This API doesn't make a lot of sense. I waste an entire network call on a refresh token operation that ends up getting thrown away, just to see if the Authorizer is valid.

**Second (more pressing) Issue**: This doesn't even work! The current MSI refresh token behavior means *that this will block application startup for 5 minutes while it's retried, until it gives up, if you execute this code outside of Azure.*

For me to get Sops to support Azure as seamlessly as GCP, I need:
* at least a `IsMSIAvailable()` that returns a true/false quickly so I can re-implement a full, working `GetAuthorizer` that tries MSI and then moves-on to CLI
* much more preferably, #541 is addressed by:
  * fixing the `Authorizer()` interface and implementations to ensure they return valid token sources
  * MSI's RefreshToken doesn't hang for 5 minutes outside Azure
  * `GetAuthorizer` tries conventional auth mechanisms based on the environment, as it does currently, then falls to MSI and then falls to CLI. Then everyone can just use this function everywhere and be done with this.

This blocks: https://github.com/mozilla/sops/pull/710

**Comment by jhendrixMSFT** [comment]
Agreed that the `Authorizer()` pattern here stinks.  Unfortunately it would be a pretty build overhaul to fix this in a non-breaking way.  FWIW this is much better in our track 2 `azidentity` package.

I think the best we can do here is fail early, avoiding retries in the case where MSI authentication isn't available.  I can also make a `MSIAvailable()` func in the `adal` package available if you want to build on top of that.

**Comment by colemickens** [comment]
Makes sense. I'm definitely intrigued about `azidentity`! 

>I think the best we can do here is fail early, avoiding retries in the case where MSI authentication isn't available. I can also make a MSIAvailable() func in the adal package available if you want to build on top of that.

Either would be great. If the former is available, I will probably just always call it. Even with that though, I can imagine the latter being useful as well if someone wanted to "warn" that MSI was available but needed to be opt-ed into, for example.

Thanks @jhendrixMSFT.

**Comment by jhendrixMSFT** [comment]
This is fixed in autorest/adal/v0.9.2
