### ISSUE TITLE
autorest/date/unixtime could not handle large dates like "9999-12-31"

### ISSUE THREAD

**Issue by njuCZ** [Azure/go-autorest#549]
the `MarshalJSON()` and `UnmarshalJSON()` func may cause int64 overflow, which cause the result not right

* `MarshalJSON()`

test code:
```
expirationDate, _ := time.Parse(time.RFC3339, "9999-12-31T00:00:00Z")
expirationUnixTime := date.UnixTime(expirationDate)
fmt.Println(time.Time(expirationUnixTime).UnixNano())
```

according to the doc: 
> // UnixNano returns t as a Unix time, the number of nanoseconds elapsed
> // since January 1, 1970 UTC. The result is undefined if the Unix time
> // in nanoseconds cannot be represented by an int64 (a date before the year
> // 1678 or after 2262). Note that this means the result of calling UnixNano
> // on the zero Time is undefined. The result does not depend on the
> // location associated with t.

I think we swould better use "Unix()" but not "UnixNano()" func

* `UnmarshalJSON()`

`NewUnixTimeFromSeconds()` will try to convert seconds to a type `time.Duration`. It will try to convert seconds to nanoseconds and then store using int64.

According to the doc:
> // A Duration represents the elapsed time between two instants
> // as an int64 nanosecond count. The representation limits the
> // largest representable duration to approximately 290 years.

So for large dates, both two functions could not work

**Comment by jhendrixMSFT** [comment]
It's unfortunate that the code treats this a Unix nano.  Given that the code has been like this for years, I worry that consumers have come to rely on the existing behavior.  We can fix this in track 2, but I'm hesitant to change the default behavior here.  How big of an issue is this really?

**Comment by jhendrixMSFT** [comment]
Closing as we won't be changing this.
