### ISSUE TITLE
Missing Release v0.9.6

### ISSUE THREAD

**Issue by stekodyne** [Azure/go-autorest#553]
It appears that the v0.9.6 release was removed/deleted.  Is that a true statement?

go get -v -t github.com/Azure/go-autorest@v0.9.6
go get github.com/Azure/go-autorest@v0.9.6: github.com/Azure/go-autorest@v0.9.6: invalid version: unknown revision v0.9.6

**Comment by jhendrixMSFT** [comment]
Hello!  This is a multi-module repo, as such there's no root module with that version.  Do you know which module you're looking for?

**Comment by stekodyne** [comment]
First, thanks for the support!

It is not really my application that is calling for the lib.  It is
Kubernates Go Client (k8s.io/client-go).  All I can really add it
seemed to build a couple of weeks ago but now it is failing with the
following.

Cannot resolve dependency:github.com/Azure/go-autorest:
commit='v0.9.6', urls=[https://github.com/Azure/go-autorest.git,
git@github.com:Azure/go-autorest.git]
Resolution stack is:
+- gitlab.skyward.cloud/cops/crunchy-proxy
 +- google.golang.org/grpc#35afeb6efe9b0d62407464a8ff1c7aabb3ee49b8
  +- github.com/envoyproxy/go-control-plane#a868a7092a876f53a650a100e982dee956420696
   +- k8s.io/client-go#5d33118d4742c7ce8c57b92d140b91d97ce7b06f

It appears it is requiring and importing the following:
require (
...
github.com/Azure/go-autorest/autorest v0.9.6
...

plugin/pkg/client/auth/azure/azure.go
import (
...
"github.com/Azure/go-autorest/autorest"
"github.com/Azure/go-autorest/autorest/adal"
"github.com/Azure/go-autorest/autorest/azure"
...

**Comment by jhendrixMSFT** [comment]
Thanks for the info.

The tag for module version `autorest/v0.9.6` is still present.  https://github.com/Azure/go-autorest/releases/tag/autorest%2Fv0.9.6  Unclear why it would suddenly stop building.  Has anything else changed recently?

**Comment by stekodyne** [comment]
Bear with me on this as I am new to Go.  Recovering Java developer.

The application I am trying to build is a bit stale, so I started to update
dependencies which is where it started blowing up. The application uses
Google gRPC lib, that in turn uses the Kubernates Go Client that uses
Azure/go-autorest.  The latest K8s.io/client-go still uses the v0.9.6
release of autorest.  It appears that the original source used Google's
gRPC v1.4.0 which did not have the dep on the Kubernates Go Client.  I also
have a ticket open with Kubernates on the use of a nonexistent release but
have not heard anything as of yet.  I was hoping for a "oh we deleted that"
type of issue.
