### ISSUE TITLE
Fallback for http.NewRequestWithContext for older Go versions

### ISSUE THREAD

**Issue by wrosenuance** [Azure/go-autorest#555]
A [recent commit](https://github.com/Azure/go-autorest/commit/cbf46deb11b50a1bc9ac059f430c647493829459) introduced a reference to `http.NewRequestWithContext`, which was added in [Go 1.13](https://golang.org/doc/go1.13).

Adding this has meant that the library no longer builds on Go 1.8, which we are trying to support in the [Go MS SQL driver](https://github.com/denisenkom/go-mssqldb), and I am trying to have Azure AD authentication merged there using autorest/adal.

Is it possible to replace this with the previous API of `http.NewRequest` combined with the `WithContext` method? Or to introduce a conditional build option that does so for older Go versions?

**Comment by jhendrixMSFT** [comment]
This has been fixed in autorest/adal/v0.9.2

**Comment by jhendrixMSFT** [comment]
There was a bug found, please use v0.9.4 instead.
