### ISSUE TITLE
Address vulnerable jwt-go dependency

### ISSUE THREAD

**Issue by xntrik** [Azure/go-autorest#568]
Hi folks,

This package currently depends on https://github.com/dgrijalva/ that has an un-patched security vulnerability. There are more details in:
* The initial bug report https://github.com/dgrijalva/jwt-go/issues/422
* A proposed PR https://github.com/dgrijalva/jwt-go/pull/429
* Ongoing conversation where they're trying to get support to merge this in https://github.com/dgrijalva/jwt-go/issues/428

I'm wondering whether it's possible to update `adal` to use another package (it seems a few places are moving to https://github.com/square/go-jose), or perhaps a fixed fork of jwt-go (https://github.com/form3tech-oss/jwt-go/)

Thanks!

**Comment by jhendrixMSFT** [comment]
Thanks for bringing this to my attention.

I looked at our usage of `jwt-go`, we only use it for signing a JWT with a certificate's private key so I believe we're not affected by this issue.

Given our limited reliance on this package it might be better to simply remove it entirely (that's what we did for track 2).  I'm looking into this.

**Comment by xntrik** [comment]
Awesome @jhendrixMSFT - thank you so much for the response

**Comment by jhendrixMSFT** [comment]
Fixed in module `autorest/adal/v0.9.5`
