### ISSUE TITLE
Error when running with MSI in App Service

### ISSUE THREAD

**Issue by nilsga** [Azure/go-autorest#574]
When running in an App Service environment, an old version of the msi api version is used (api-version=2017-09-01), which returns `expires_on` as a timestamp. However, it appears that the deserialization expects this to be of Number type, and the request fails with `Error: adal: Failed to unmarshal the service principal token during refresh. Error = 'json: invalid number literal, trying to unmarshal "\"10/08/2020 07:45:49 +00:00\"" into Number'`.

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest/adal/v0.9.6`
