### ISSUE TITLE
getURLFromLocationHeader should allow relative URLs

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/go-autorest#576]
Scenario: I'm using go-autorest to invoke an ARM method to create a user identity at `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{resourceName}`. The response is 201 and contains a `Location` header e.g. `/subscriptions/01fedcba-7a9e-424b-80b2-96babd57a8a1/resourcegroups/myrg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/example`.

A further call to 

```
future, err := azure.NewFutureFromResponse(resp)
...
err = future.WaitForCompletionRef(ctx, k.client)
```

fails with

```
azure#getURLFromLocationHeader: invalid polling URL '/subscriptions/01fedcba-7a9e-424b-80b2-96babd57a8a1/resourcegroups/myrg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/example': StatusCode=0
```

because `getURLFromLocationHeader` demands the URL to be absolute in https://github.com/Azure/go-autorest/blob/bf140ad4ab62921cd264efe85cadcf8353d5a364/autorest/azure/async.go#L895-L905

Is this a supported scenario? Should relative URLs be supported as per the RFC? https://tools.ietf.org/html/rfc7231#section-7.1.2

**Comment by jhendrixMSFT** [comment]
Hello!  According to the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/msi/resource-manager/Microsoft.ManagedIdentity/stable/2018-11-30/ManagedIdentity.json#L180) this operation isn't a long-running operation so there should be no need to create a `Future` from the response (the fact it returns a `Location` header is a bit strange).  Is the user-assigned identity not actually created when the REST call returns?

Also, just in case you were unaware, the Go SDK contains an [API](https://github.com/Azure/azure-sdk-for-go/blob/master/services/msi/mgmt/2018-11-30/msi/userassignedidentities.go#L50) for creating user-assigned identities if you're able to use it.

**Comment by mikhailshilkov** [comment]
Thank you @jhendrixMSFT for your response! For context, I'm working on the [Pulumi Azure NextGen provider](https://www.pulumi.com/blog/announcing-nextgen-azure-provider/) where we generate our SDK from the whole surface of ARM based on Open API specs.

I take your suggestion regarding a long-running operation, but so far we haven't seen any downsides of creating a `Future` for any operation. Am I missing something important? (other than this particular issue)

Apart from that, do you think the location handling of `go-autorest` is correct in this scenario?

**Comment by jhendrixMSFT** [comment]
Thanks for the link, I will check this out.

Azure long-running operations (LROs) are annotated in swagger with the [x-ms-long-running-operation](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-long-running-operation) extension.  See an example in the latest spec for [compute](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L948).  You should only need to construct a `Future` for such operations, all others are synchronous thus a `Future` isn't required.

It could be the case that the APIs for user-assigned identities are missing this annotation (it wouldn't be the first time I've seen this).  I will see if I can find more info about this.

**Comment by mikhailshilkov** [comment]
> it wouldn't be the first time I've seen this

Yeah, that's partly why we took a shortcut and construct a Future for all responses, and that seemed to work fine so far.

> It could be the case that the APIs for user-assigned identities are missing this annotation

It wouldn't solve the issue in question, right? It's more of whether the location header is valid and whether it's handled correctly.

**Comment by jhendrixMSFT** [comment]
You are correct in that this would be broken.  However, reading the [ARM RPC spec](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#asynchronous-operations) it looks like the returned polling URL might need to be absolute (it's a bit vague but could be interpreted in such a way; to-date, I've not seen a relative polling URL and our `go-autorest` runtime doesn't support it).  I will follow up on this.

**Comment by jhendrixMSFT** [comment]
I dug into this a bit more, the API appears to be synchronous; i.e. after calling it the user-defined identity is created successfully and is returned by the endpoint.

I've asked the service team about the `Location` header being returned but haven't heard back yet.  At any rate I don't think that creating a `Future` from this response is necessary.

**Comment by mikhailshilkov** [comment]
We switched off creating a `Future` for this request, thank you for all the suggestions
