### ISSUE TITLE
Azure App Service fails with MSI to access Key Vault

### ISSUE THREAD

**Issue by alicejgibbons** [Azure/go-autorest#577]
**Issue:**
Attempting to use a User Assigned Managed Identity in App Service fails when trying to access a secret from KeyVault. Tried both the [NewAuthorizerFromEnvironment()](https://github.com/Azure/azure-sdk-for-go/blob/1d08536e03f9ff6d3d244dbd852006534071e973/services/keyvault/auth/auth.go#L31) and [Authorizer()](https://github.com/Azure/go-autorest/blob/autorest/azure/auth/v0.5.3/autorest/azure/auth/auth.go#L723) implementations. The same container and MSI configuration works running in Azure Container Instances but fails in App Service (custom container).

**Version:**
v0.11.10

**Fails with:** 
_azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://aggolang-msi-old-LNWC-kv.vault.azure.net/secrets/test-secret/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"statusCode":400,"message":"Unable to load requested managed identity.","correlationId":"51942452-3a05-4c1e-8571-2d93e6a7e6af"}_

**App Service Logs:**
![image](https://user-images.githubusercontent.com/14792988/98575379-5efc2400-2276-11eb-8653-3616367ab90e.png)

**Code & Infra config for repro:** 
https://github.com/sgettys/azure-go-msi

@sgettys @robece @catalinaperalta

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest/adal/v0.9.6`
