### ISSUE TITLE
🐛 NewAuthorizerFromEnvironment never fails

### ISSUE THREAD

**Issue by Porges** [Azure/go-autorest#580]
Even with an empty environment, [`NewAuthorizerFromEnvironment`](https://github.com/Azure/go-autorest/blob/f7ec17d62576b689bfc665ead655066c00c9d363/autorest/azure/auth/auth.go#L62) returns an authorizer, as the MSI authorizer is always returned as a fallback. This is poor behaviour as the caller cannot know if the authorizer is set up correctly or not. I think that, as a minimum, the MSI authorizer requires that a Client ID is set.

At the very least, `NewAuthorizerFromEnvironment` should report all missing environment variables for the authorizer type that it decides to return.

**Comment by jhendrixMSFT** [comment]
The design was contentious but it landed where it is for better or worse.  The thinking at the time was to provide a simple authorizer that would "just work" when transitioning from a dev machine to Azure with zero code change (I highly requested feature from customers).

The other problem here is the lazy evaluation of the authorizers.  This creates a case where you will always receive an MSI authorizer even if you're not running in Azure.

MSI only requires a client ID if you're using a user-assigned identity; it's not required for system-assigned identity.

We've improved on this in our new [azidentity](https://github.com/Azure/azure-sdk-for-go/tree/master/sdk/azidentity) module which will eventually replace the `auth` and `adal` packages in `go-autorest`.  It can be used today with our track 1 SDK via the [azidext](https://github.com/jongio/azidext/tree/master/go/azidext) module.

I will add some logging to `NewAuthorizerFromEnvironment()` to help diagnose the credentials used.

**Comment by Porges** [comment]
Thanks @jhendrixMSFT, `azidentity` looks promising and I’ll try it out.

**Comment by jhendrixMSFT** [comment]
There's an example using `azidentity` via the adapter [here](https://github.com/Azure/azure-sdk-for-go/tree/master/sdk/samples/azidentity/SDKV1Adapter).

**Comment by jhendrixMSFT** [comment]
Logging has been added in `autorest/azure/auth/v0.5.4`
