### ISSUE TITLE
Environment: MicrosoftGraphEndpoints

### ISSUE THREAD

**Issue by miosmian** [Azure/go-autorest#585]
Currently the `Environment.GraphEndpoint` corresponds to `"https://graph.windows.net/",` (other cloud endpoints follow this format) but the new microsoft graph unified api endpoint is not in this struct. Are there plans to add this? It would be,

`Environment.GraphEndpoint = "https://graph.microsoft.com/",`  (public cloud)
`Environment.GraphEndpoint = "https://graph.microsoft-ppe.com/",` (ppe)
 and others for Gov..etc clouds?

**Comment by jhendrixMSFT** [comment]
The current graph endpoints are for AAD graph which is different from Microsoft Graph.  We can add them, but the existing ones will remain the same.

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest@v0.11.26`
