### ISSUE TITLE
Key vault GetSecret does not return error for invalid key vault URL

### ISSUE THREAD

**Issue by ericajlin** [Azure/go-autorest#588]
The key vault get secret method, ie: `Client.GetSecret(ctx, vaultURL, secretName, secretVersion)` normally returns an error for invalid secret, or insufficient permissions to secrets get. However, if the vault URL does not exist, the call essentially 'hangs' and does not return until the context is cancelled.
The expected behavior is for the call to return an error right away with reason "Key vault URL is invalid"

**Comment by jhendrixMSFT** [comment]
What's happening here is that the retry policy is seeing the non-nil error returned from the HTTP client (a `*net.DNSError`) and retries the operation.  Eventually it will hit the retry cap and fail the request.

This is a bit of a tricky problem to solve, as we've seen cases where a DNS name transiently fails to resolve.  So the transient and non-transient cases are ambiguous, i.e. how do you know that retrying on a `*net.DNSError` won't succeed?

**Comment by jhendrixMSFT** [comment]
For key vault, if you need to verify that the vault exists you can use the `VaultsClient.CheckNameAvailability()` method from management plane.

https://github.com/Azure/azure-sdk-for-go/blob/master/services/keyvault/mgmt/2019-09-01/keyvault/vaults.go#L49

```go
	client := keyvault.NewVaultsClient(subscriptionID)
	client.Authorizer = authorizer
	available, err := client.CheckNameAvailability(context.Background(), keyvault.VaultCheckNameAvailabilityParameters{
		Name: to.StringPtr(vaultName),
		Type: to.StringPtr("Microsoft.KeyVault/vaults"),
	})
	if err != nil {
		// handle error....
	}
	fmt.Println(*available.NameAvailable)
```

We cannot change the retry policy without impacting reliability.
