### ISSUE TITLE
Function App MSI token failed to parse expires_on date format

### ISSUE THREAD

**Issue by btHolert** [Azure/go-autorest#593]
When generating a ServicePrincipalTokenFromMSI in Azure Function App and then calling EnsureFresh() this error happens:
`parsing time "12/09/2020 16:12:09 +00:00" as "1/2/2006 15:04:05 PM +00:00": cannot parse "0:00" as "PM"`

Code:
```
msiEndpoint, err := adal.GetMSIEndpoint()
if err != nil {
	return nil, err
}

callback := func(t adal.Token) error {
	return nil
}

token, err = adal.NewServicePrincipalTokenFromMSI(msiEndpoint, resourceId, callback)
if err != nil {
	return nil, err
}

err = token.EnsureFresh()
if err != nil {
	return nil, err
}
```

This error happens at https://github.com/Azure/go-autorest/blob/6afd852870d16ce46bf25dfc4c995cc036314afd/autorest/adal/token.go#L1030

It seems like the expiresOnDateFormat wrong there ?

Go version: 1.15.4
go-autorest/autorest version: v0.11.12 // indirect
go-autorest/autorest/adal version: v0.9.8

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest/adal v0.9.9`

Thanks for the bug report.
