### ISSUE TITLE
client.RetryAttempts should probably be client.Attempts, or behavior changed

### ISSUE THREAD

**Issue by devigned** [Azure/go-autorest#597]
The behavior of `autorest.Client.RetryAttempts` is such that if you set `c.RetryAttempts = 0` it will cause a panic since the response will be nil when calling `azure.createPollingTracker(resp)` via `azure.NewFutureFromResponse(resp *http.Response) (Future, error)`. With that name, I'd expect `0` to attempt to make the first request, then not attempt to retry a failure.

**Comment by jhendrixMSFT** [comment]
This is unfortunate.  I can update the doc string to clarify the behavior here however I'm hesitant to make any behavior change as it's been like this for years.

**Comment by devigned** [comment]
> however I'm hesitant to make any behavior change as it's been like this for years.

Agreed. A behavioral change without a compiler notification would be the worst.

Idk, maybe at some point it could be replaced or deprecated. Really, just wanted to open it up so it was easy to find is someone ran into the issue.

**Comment by jhendrixMSFT** [comment]
Updated the doc string in `autorest/v0.11.14` to clarify how this works.

FWIW this has been fixed in `azcore` so our track 2 SDKs don't have this weirdness.
