### ISSUE TITLE
'az' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by slyons** [Azure/go-autorest#601]
This is a cross-posted issue from [here](https://github.com/databrickslabs/terraform-provider-databricks/issues/447) after I've done some digging. It took me a little while as I'm not familiar with Golang.

I can't use the CLI module (or others that depend on it) from within a Python virtualenv. The workaround that I think you've put in place doesn't seem to work, either.

I've set the environment variable to be the path to the virtualenv version of the script, but it still fails to locate it.

```console
❯ $env:AzureCLIPath
C:\Users\scott\anaconda3\envs\myenv\Scripts\az.bat
```

```console
> terraform apply
...

Error: Invoking Azure CLI failed with the following error: 'az' is not recognized as an internal or external command,
operable program or batch file.
```

This only occurs on Windows, both Command and Powershell.

**Comment by jhendrixMSFT** [comment]
The value in `AzureCLIPath` is appended to the `PATH` for the shell used to launch `az` so it shouldn't contain the `\az.bat` part.  Can you try that and see if it works?

**Comment by jhendrixMSFT** [comment]
Closing.  Please ping back if this is still an issue.
