### ISSUE TITLE
azidentity guidance

### ISSUE THREAD

**Issue by colemickens** [Azure/go-autorest#611]
Hi!

I've just seen the information in https://github.com/Azure/go-autorest/issues/580. The new `azidentity` module looks great.

Is there recommendation for consumers of the Go SDK, in terms of what to use? For example, `sops` has Azure integration, and most of that code is currently just the auth handling. I've got a PR in progress to add seamless MSI support, but I am wondering if I should go ahead and overhaul it to use `azidentity`.

I assume the `azure-go-sdk` will eventually only use `azidentity` and over time the need for the `azidext` adapter will go away? What is the recommendation for developers, today? Will this change in the future? Any idea of timeline?

Thanks a bunch!

**Comment by jhendrixMSFT** [comment]
`azidentity` is indeed the future, and we have a handful of ring-zero management services modules available that natively use it (i.e. no `azidext` required).  You can find them [here](https://github.com/Azure/azure-sdk-for-go/tree/master/sdk/arm).

As for using `azidentity`, while we (the Go SDK team) would love for you to use it, I must point out that it's still in preview and hasn't really been tested at scale (we have pretty comprehensive unit tests and have performed a lot of manual end-to-end tests, but this doesn't always catch bugs that appear under load).  Also, we are still refining the public surface area so their might be the occasional breaking change although we try to avoid that if possible (we rev the minor version number in this case).  That said, if you decide to use it and find bugs or have questions/comments on the APIs, please open an issue in the `azure-sdk-for-go` repo, add tags `Azure.Identity` and tag @catalinaperalta

**Comment by jhendrixMSFT** [comment]
Closing as I believe this has been answered.  Please ping back if you have more questions.
