### ISSUE TITLE
Latest version breaks CloudShell authentication

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/go-autorest#612]
The recent changes to support MSI in App Service and Function Apps have broken CloudShell authentication, which also specifies the MSI Environment Variable [used in this function to check if `go-autorest` is being run inside an AppService/Function App](https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L885-L896):

<img width="477" alt="Screenshot 2021-01-25 at 07 23 40" src="https://user-images.githubusercontent.com/666005/105668745-40eda980-5ede-11eb-9436-1d405c837a77.png">

Which means attempting to load the MSI token leads to:

```
azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/f6d69ee2-34d5-4ca8-a143-7a2fc1aeca55/providers?api-version=2016-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":{"code":"bad_request_102","message":"Required metadata header not specified"}} Endpoint http://localhost:50342/oauth2/token?api-version=2017-09-01&resource=https%3A%2F%2Fmanagement.azure.com%2F
```

This happens because the `metadata` header is conditionally set based on whether this is/isn't an ASE:

https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L952-L954

Upstream issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/10292

**Comment by jhendrixMSFT** [comment]
Our support for cloud shell in `go-autorest` is shaky at best, the fact that it happened to work is purely coincidental.  I will look at getting this fixed.

On a side-note, perhaps as a very first step towards track 2, you can evaluate [`azidentity`](https://github.com/Azure/azure-sdk-for-go/tree/master/sdk/azidentity) for authentication in TF?  It has first-class support for cloud shell and other forms of authentication (see the README for the complete list).  It will work with track 1 via the [`azidext`](https://github.com/jongio/azidext/tree/master/go/azidext) adapter.

**Comment by jhendrixMSFT** [comment]
Fixed in module `github.com/Azure/go-autorest/autorest/adal@v0.9.11`

**Comment by jhendrixMSFT** [comment]
`github.com/Azure/go-autorest/autorest/azure/auth/@v0.5.7` now uses the fixed `adal` module.
