### ISSUE TITLE
Odd error appearing: TypeError: Cannot read property 'language' of undefined

### ISSUE THREAD

**Issue by scseely** [Azure/go-autorest#619]
When running the following command line:

`autorest --go .\saas.md --go-sdks-folder=.\out --use=@autorest/go@4.0.0-preview.11 --add-credentials --verbose`

I get the error:
`FATAL: TypeError: Cannot read property 'language' of undefined`

I can't figure out where "language" should be appearing to address this issue. Any pointers would be handy.

I can eliminate the OpenAPI spec as being an issue. The spec I am using currently works fine with C#, Python, Java, and TypeScript: [Marketplace SaaS API v2](https://raw.githubusercontent.com/microsoft/commercial-marketplace-openapi/main/Microsoft.Marketplace.SaaS/2018-08-31/saasapi.v2.json)

The SaaS.md file can be viewed in the gist at https://gist.githubusercontent.com/scseely/dcd7728eae4b383d924f248253cd54d5/raw/08e49c41331e862069143a845a0b2d8887a47f41/saas.md which appears as markdown at https://gist.github.com/scseely/dcd7728eae4b383d924f248253cd54d5. 

If the autorest Go provider doesn't understand credential-scopes yet or --add-credentials, I'll survive and just write the helper code. scseely@microsoft.com if you need to contact me directly. Thanks!

**Comment by scseely** [comment]
Some more details: this error appears to be linked to pageable responses. 

Issue is in transform.js, the code fails since the error cases for the OpenAPI spec do not have collection based responses. 

Another issue is that getStatusCodes in @autorest_go@4.0.0-preview.11\node_modules\@autorest\go\dist\generator\helpers.js does not handle the 403 status code (Forbidden). 

I have a few changes ready to address this locally, but am not able to find the github repo for the generator code. Pointers appreciated. scseely@microsoft.com if you need to contact me.

**Comment by jhendrixMSFT** [comment]
The code for the track 2 code generator can be found in the `track2` branch in the [autorest.go](https://github.com/Azure/autorest.go) repo.

I took a look at the linked swagger, there are some response sections that include 4xx and 5xx response codes but are missing the [`x-ms-error-response`](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-error-response) annotation which I believe is the underlying source of the error.  While we could fix the code generator to not crash, the swagger is still malformed and would likely not generate the code you want.

I will get a fix in to add `http.StatusForbidden` to the list of error codes.

**Comment by jhendrixMSFT** [comment]
Fixed in v4.0.0-preview.13
