### ISSUE TITLE
I need to get the claims from an user's access token 

### ISSUE THREAD

**Issue by ariasf** [Azure/go-autorest#623]
So i got this example running with AD B2C .  Users can signup and signin, it also generates Bearer Access Tokens. 
sample app: https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa
I have a go Custom Handler in Azure Function I want to get the Authorization header that has the bearer token, and using this pkg or another go pkg  get the claims of the token. 

any help or guidance is appreacited I'm new to Azure coming from AWS.

**Comment by jhendrixMSFT** [comment]
Sorry for the long delay.

I don't know if you found a solution, but you can parse the bearer token using the `https://github.com/golang-jwt/jwt` package.  Something like this.

```go
jj, _ := jwt.Parse(bearerToken, nil)
claims := jj.Claims.(jwt.MapClaims)
```

Please ping back if you have further questions.
