### ISSUE TITLE
Intermittent error

### ISSUE THREAD

**Issue by palladia** [Azure/go-autorest#626]
Just within last week or so, we've been seeing this error intermittently, in calls to adal.NewServicePrincipalToken() and/or refresh(). It only seems to happen on Linux.

Error details:%!!(MISSING)(EXTRA string=adal: Refresh request failed. Status Code = '400'. Response body: {\\\"error\\\":\\\"unauthorized_client\\\",\\\"error_description\\\":\\\"AADSTS700016: Application with identifier 'xxxxxxxx-xxxx-44cc-b423-dd3cd793450e' was not found in the directory 'xxxxxxxx-xxxx-41af-91ab-2d7cd011db47'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\\\\r\\\\nTrace ID: xxxxxxxx-xxxx-40c1-8010-4c91fa59c500\\\\r\\\\nCorrelation ID: xxxxxxxx-xxxx-464b-8f91-8e9545f8e1ec\\\\r\\\\nTimestamp: 2021-04-13 18:17:47Z\\\",\\\"error_codes\\\":[700016],\\\"timestamp\\\":\\\"2021-04-13 18:17:47Z\\\",\\\"trace_id\\\":\\\"xxxxxxxx-xxxx-40c1-8010-4c91fa59c500\\\",\\\"correlation_id\\\":\\\"xxxxxxx-xxxx-464b-8f91-8e9545f8e1ec\\\",\\\"error_uri\\\":\\\"https://login.windows.net/error?code=700016\\\"} 

If we re-run, the error does not re-appear.  It seems like a timing issue, but we are unsure.  We tried upgrading to latest ADAL, but still seeing this occassionally.  Any help?

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.  The error is server-side, I don't think this is an SDK issue.  Please ping if you have more info.
