### ISSUE TITLE
[Event Grid Key Authorizer] Support aeg-sas-token for authentication

### ISSUE THREAD

**Issue by shrutir25** [Azure/go-autorest#627]
Azure Event Grid supports authentication via SAS token using aeg-sas-token header. See https://docs.microsoft.com/en-us/azure/event-grid/security-authentication for more details. But the EventGridKeyAuthorizer recognises only topicKey and sets only aeg-sas-key header here - https://github.com/Azure/go-autorest/blob/master/autorest/authorization.go#L266

**Comment by shrutir25** [comment]
@jhendrixMSFT Can I get an update on this Issue ?

**Comment by jhendrixMSFT** [comment]
I believe this is the correct link.

https://docs.microsoft.com/en-us/azure/event-grid/authenticate-with-access-keys-shared-access-signatures

We are no longer adding new features to our track 1 SDKs.  However, you should be able to implement this yourself.  All that's required is to create a type that satisfies the `autorest.Authorizer` interface.  I took a stab at an initial implementation [here](https://gist.github.com/jhendrixMSFT/6647e7fb4c7fff8f228d076795d93aa5).
