### ISSUE TITLE
panic: interface conversion: http.RoundTripper not *http.Transport

### ISSUE THREAD

**Issue by uvw** [Azure/go-autorest#629]
The library panics at https://github.com/Azure/go-autorest/blob/master/autorest/adal/sender.go#L76 when the caller had `http.DefaultTransport` replaced with a custom RoundTripper, which is quite common for global tracing/debugging purposes. 

Usually, it is not expected from a library to panic unless explicitly documented (e.g., `Must*` functions). Would it be possible to handle this case gracefully? At least preventing the panic, for instance, fall back to new `http.Transport` and emit a warning if there is a type mistmatch.

**Comment by jhendrixMSFT** [comment]
Fixed in `adal/v0.9.16`
