### ISSUE TITLE
Allow to specify --subscription flag for GetTokenFromCLI

### ISSUE THREAD

**Issue by ekini** [Azure/go-autorest#632]
We have multiple subscriptions that we manage, and trying to use https://github.com/Azure/go-autorest/blob/master/autorest/azure/cli/token.go#L126 to get the token from the logged in az cli.

However, the subscription id is not configurable, so we have to switch it again and again when working on multiple projects.

Proposal:
Add another function alongside https://github.com/Azure/go-autorest/blob/master/autorest/azure/cli/token.go#L126 to accept subscription id flag.

Happy to make a PR for that, shouldn't be hard.

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest/azure/cli/v0.4.3`
