### ISSUE TITLE
MSAL Support?

### ISSUE THREAD

**Issue by princjef** [Azure/go-autorest#636]
With [the push to migrate from ADAL to MSAL](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration), has there been any discussion of moving this module and the clients generated with it (such as those in the Azure SDK for Go) from ADAL/v1.0 to MSAL/v2.0 for auth? ADAL stopped receiving new features a year ago.

It looks like the AAD team has an early preview of an official MSAL package for golang which may be useful rather than trying to reimplement the auth patterns already present in this repository: https://github.com/AzureAD/microsoft-authentication-library-for-go. With that said, that package seems to be in evaluation mode right now, so I'm not sure what steps would be needed to integrate it.

**Comment by jhendrixMSFT** [comment]
Our updated authentication module is [`azidentity`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity), and while it doesn't use MSAL at present, it will at some point.
We won't be migrating the content in `go-autorest` to use MSAL as it will be retired in favor of `azidentity`.

**Comment by shueybubbles** [comment]
Let's say we wanted to contribute full AAD auth support to the [go-mssql driver](https://github.com/denisenkom/go-mssqldb) to simplify Go app development against Azure SQL Database and Managed Instance.
1. Which of the various Go libraries (azidentity, autorest\adal, msal for go) should we use as the long term solution in such an integration?
2. Should we (Sql team at Microsoft) register a first party client id for the go-mssql driver to relieve the burden on every user of it from having to register an app to connect to SQL DB? IE can we follow the same model `Microsoft.Data.SqlClient` followed?

**Comment by jhendrixMSFT** [comment]
@shueybubbles sorry for the delay.

For your first bullet, `azidentity` is the path forward for AAD authentication.

I don't have an answer to your second bullet, might be worth following up internally with additional people to find the right solution.

**Comment by jhendrixMSFT** [comment]
Closing as we won't be adding MSAL support to `go-autorest`.  We can follow up on any other items separately.
