### ISSUE TITLE
autorest/adal parseExpiresOn inconsistent return value

### ISSUE THREAD

**Issue by mdgreenfield** [Azure/go-autorest#638]
@jhendrixMSFT, I'm a little confused why [`parseExpiresOn()`](https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L1097-L1115) calculates the difference between `t time.Time` (the passed in and parsed `s string`) and `time.Now().UTC()`. That difference I believe is effectively the `expires_in` value (the TTL of the token).

However, when the `strconv.ParseInt(s, 10, 64)` logic is successful this `parseExpiresOn` function would be passing through the unix timestamp as far as I can tell (i.e. the actual time when the token expires and not the `expires_in` value).

That is, if a unix timestamp is passed in, a unix timestamp is returned. If a string formatted datetime is passed in a remaining TTL is returned.

From the IMDS docs - https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http

> expires_on - The timespan when the access token expires. The date is represented as the number of seconds from "1970-01-01T0:0:0Z UTC" (corresponds to the token's `exp` claim).

**Comment by jhendrixMSFT** [comment]
You're right, looks like the number format got confused with `expires_in`, so we're treating the unix timestamp as the number of seconds. :(

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest/adal/v0.9.10`
