### ISSUE TITLE
Replace github.com/form3tech-oss/jwt-go with https://github.com/golang-jwt/jwt?

### ISSUE THREAD

**Issue by brackendawson** [Azure/go-autorest#642]
The maintained fork of https://github.com/dgrijalva/jwt-go seems now to be https://github.com/golang-jwt/jwt, can [go-autorest/autorest/adal](https://github.com/Azure/go-autorest/blob/76c7860e9b602854c8598676b7550c715c48a607/autorest/adal/go.mod#L11) move to this fork now?

This request stems from distribution/distribution#3361, we import this repository via https://github.com/Azure/azure-sdk-for-go and we would like to settle on the most likely to be maintained fork.

**Comment by dims** [comment]
+1 from me. I see the same request in https://github.com/Azure/go-autorest/pull/570#issuecomment-857445942 as well

**Comment by brackendawson** [comment]
So a good reason to do this is that v3.2.4 of form3tech-oss/jwt-go that contains a vulnerability fix is not importable, it was given an invalid go.mod file which should have had a version in its module line.

**Comment by thaJeztah** [comment]
Quick attempt at unifying them again; https://github.com/golang-jwt/jwt/pull/40
