### ISSUE TITLE
MSI Support for Azure ARC enabled machines

### ISSUE THREAD

**Issue by mb290** [Azure/go-autorest#644]
I am attempting to use a solution which has the go-autorest SDK to authenticate to Azure using a Managed Identity on an ARC enabled server. Currently the Go client is looking for the existing MSI_ENDPOINT, but I was wondering if there was any plans for the Go-Autorest SDK to support IDENTITY_ENDPOINT and IMDS_ENDPOINT? Details can be found at [https://docs.microsoft.com/en-us/azure/azure-arc/servers/managed-identity-authentication](https://docs.microsoft.com/en-us/azure/azure-arc/servers/managed-identity-authentication)

**Comment by jhendrixMSFT** [comment]
We support Azure ARC in our new authentication module [`azidentity`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) which supersedes the authentication mechanisms found in `go-autorest`.  If you're using our current Azure SDK for Go, we have an adapter [here](https://github.com/jongio/azidext/tree/master/go/azidext) that allows you to seamlessly use `azidentity` with our SDK.

**Comment by jhendrixMSFT** [comment]
Closing as we won't be adding ARC support in `go-autorest`.
