### ISSUE TITLE
On Behalf Of Authorization Flow

### ISSUE THREAD

**Issue by yogilad** [Azure/go-autorest#647]
We have a customer trying to access Kusto service from his Go Web Application. 
The customer would like to employ the On-Behalf-Of authentication flow, but this does not seem to be available in go-autorest.

We have looked into MSAL library as well and it does not seem to be implement nor does it seem to be MSAL's mature enough to convince him to migrate from ADAL.

Will it be possible to implement the on behalf of flow in go-autorest?
The customer is willing to contribute the code but he needs guidence which we can really provide well.

**Comment by jhendrixMSFT** [comment]
Hello!  We will be retiring `go-autorest` in favor of our new authentication module [`azidentity`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity), which will eventually be built on top of MSAL which will be adding support for OBO.  We won't be back-porting any of these features to `go-autorest`.
