### ISSUE TITLE
ESTSR / Regional AAD Endpoint Usage

### ISSUE THREAD

**Issue by miosmian** [Azure/go-autorest#656]
Does the autorest adal package support ESTSR regional AAD endpoints today? Currently, the global ESTS endpoint is:

```
https://login.microsoftonline.com/
```

The ESTSR endpoint would be:
```
https://<REGION>.login.microsoftonline.com/
```

We could add this manually by changing the AAD endpoint to use in the oauthconfig but wanted to check here to see if this is a supported scenario or planned to be?

**Comment by jhendrixMSFT** [comment]
You should be able to specify an ESTSR endpoint as you describe.  Can you let me know if it works?

We won't be adding any new features to support this in `go-autorest`.  Going forward, all authentication will be done via [`azidentity`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) as part of our track 2 transition.

**Comment by jhendrixMSFT** [comment]
Please ping back if there are further questions.
