### ISSUE TITLE
Add support for federated authentication

### ISSUE THREAD

**Issue by chrisst** [Azure/go-autorest#671]
The recently added federated identity workflow will allow users to pass in an externally generated JWT to exchange for a Azure oauth token. Ref: https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation

Can support for this workflow be added so that an service principal token can be constructed from a JWT ?

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest/adal@v0.9.19`
