### ISSUE TITLE
Support Synapse in USGovernmentCloud

### ISSUE THREAD

**Issue by lucashby** [Azure/go-autorest#687]
Please update the environments to support Synapse in USGovernmentCloud for Azure.

We are using Synapse in USGovernmentCloud and really need to be able to create resources under our Synapse resource through Terraform, but are unable to do so because the environments say it is not supported even though we are currently using it.

Issue from Terraform provider:  https://github.com/hashicorp/terraform-provider-azurerm/issues/15443

**Comment by jhendrixMSFT** [comment]
Fixed in `autorest@v0.11.26`

**Comment by lucashby** [comment]
> Fixed in `autorest@v0.11.26`

Can this also be fixed in the v14.x.x releases?  I don't understand the difference between the 0.x.x releases and 14.x.x releases, but I do see the downstream provider depends on 0.x.x but ends up with an indirect dependency on 14.x.x.

**Comment by jhendrixMSFT** [comment]
The `v14` releases are from pre-Go modules when we used `dep` for dependency management.

The indirect dependency you're seeing is a result of "carving out" the `autorest` (and other) modules from the monolithic release.  It's not actually used for anything, so moving to `autorest@v0.11.26` should be sufficient.
