### ISSUE TITLE
adal.token.EnsureFresh threw unmarshal error on `expires_on` field

### ISSUE THREAD

**Issue by northtyphoon** [Azure/go-autorest#696]
The following code tried to decode an int field (expires_on) to string and threw error.

https://github.com/Azure/go-autorest/blob/49906996bd99c5b2dfa96a0ff9ed4756c649dfa6/autorest/adal/token.go#L1108

'json: cannot unmarshal number into Go struct field .expires_on of type string' JSON = '{"access_token":"","refresh_token":"","expires_in":86399,"expires_on":1652886678,"not_before":1652799978,"resource":"[https://management.azure.com/","token_type":"Bearer"}'](https://management.azure.com/%22,%22token_type%22:%22Bearer%22%7D%27)

**Comment by jhendrixMSFT** [comment]
Fixed in `adal@v0.9.20`
