### ISSUE TITLE
Enable SN+I (Subject name/Issuer) authorization through certificates 

### ISSUE THREAD

**Issue by priyanka19-98** [Azure/go-autorest#702]
To enable (SN+I) based approach, we need to set: **"SendX5c" :  "true"** , if we want to generate the token through certificate. But looks like currently there is no way to do that, or am I missing something?

Basically I am looking for something: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ClientCertificateCredentialOptions

**Comment by jhendrixMSFT** [comment]
Looks like we implicitly set the `x5c` header when signing the JWT.

https://github.com/Azure/go-autorest/blob/main/autorest/adal/token.go#L262

This isn't my area of expertise though.  @chlowell is there anything additional that needs to happen?

**Comment by jhendrixMSFT** [comment]
For full SNI support please use `azidentity`.  This module is in maintenance mode so we aren't adding any new features.
