### ISSUE TITLE
Migrate tracing to OpenTelemetry

### ISSUE THREAD

**Issue by johananl** [Azure/go-autorest#703]
https://opentelemetry.io/ has been formed as a joint effort of the OpenCensus and OpenTracing projects and is the new community standard for tracing.

Given that the code is currently instrumented with OpenCensus, we should migrate to OpenTelemetry. There is a [bridge](https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/README.md) which allows switching to OpenTelemetry easily, without having to reinstrument the entire codebase.

**Comment by jhendrixMSFT** [comment]
Please ping back if you have further questions.
