### ISSUE TITLE
Generalized Support for Azure Stack

### ISSUE THREAD

**Issue by boumenot** [Azure/go-autorest#72]
@colemickens - I would like your opinion on this.

We've had a [request][1] from the Packer community to support Azure Stack.  My thinking is that the user of Packer creates a JSON document detailing their [Environment][2].  Packer can then deserializes the JSON, and the code has an Environment instance appropriate to them.  I think the only change I have to on make is to add the appropriate annotations on the existing Environment type.  Does this make sense?  If so, I will prepare a PR with the change.

[1]: https://github.com/mitchellh/packer/issues/3648
[2]: https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go

**Comment by colemickens** [comment]
Sounds sane to me. Do you know what the other SDKs are doing in this area?

**Comment by boumenot** [comment]
The Azure/autorest-clientruntime-for-java uses a type.  The type is [pre-defined to Public and China][1].

[1]: https://github.com/Azure/autorest-clientruntime-for-java/blob/master/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java#L42-56

As a consumer of the API you can re-constitute the type any way you want, and then pass it where appropriate.

**Comment by colemickens** [comment]
Looks similar to what we're doing and what you're proposing. Still sounds good to me.

**Comment by boumenot** [comment]
The implementation is similar for ruby and C#.

1. [Ruby][https://github.com/Azure/autorest/blob/master/ClientRuntimes/Ruby/ms-rest-azure/lib/ms_rest_azure/active_directory_service_settings.rb#L20-37]
1. [C#][https://github.com/Azure/autorest/blob/master/ClientRuntimes/CSharp/Microsoft.Rest.ClientRuntime.Azure.Authentication/ActiveDirectoryServiceSettings.cs#L31-39]

I think the JSON annotations make sense based on the other implementations.

One thing of note is that go-autorest exposes far more endpoints than the other SDKs.  I only see:

1. Authentication Endpoint
1. Token Audience

Whereas the go-autorest list is much more complete.  The go-autorest library has US Government, and the others do not.

**Comment by boumenot** [comment]
I'll create a PR.
