### ISSUE TITLE
Should WithPathParameters Automatically Handle Encoding?

### ISSUE THREAD

**Issue by boumenot** [Azure/go-autorest#78]
The code today expects the called to encode any path parameters ahead of time.  Is it more reasonable for the WithPathParameters to do so.  I tend to think so, but there may be valid reasons not to.

Thoughts?

``` golang
       p := map[string]interface{}{
        "secret-name": autorest.Encode("path", secretName),
    }
    q := map[string]interface{}{
        "api-version": AzureVaultApiVersion,
    }

    req, err := autorest.Prepare(
        &http.Request{},
        autorest.AsGet(),
        autorest.WithBaseURL(client.getVaultUrl(vaultName)),
        autorest.WithPathParameters("/secrets/{secret-name}", p),
        autorest.WithQueryParameters(q))

```

cc: @paulmey [source issue](https://github.com/mitchellh/packer/pull/3716)

**Comment by brendandixon** [comment]
@boumenot My memory may fail me here, but I believe which require encoding depends on values in the corresponding Swagger. The calls to encode are dynamically added.

**Comment by garimakhulbe** [comment]
@boumenot Yes, we are adding Encode when there are path parameters. But I think you are suggesting to move Encode in WithPathParameters. There might be some reason I kept it like this. I will look into this and see if we can change this.

**Comment by vishrutshah** [comment]
@garimakhulbe Could you please follow up and help us decide whether we should fix this or not.

**Comment by mcardosos** [comment]
[Here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-skip-url-encoding) it is better explained. This can be fixed, but I think it is not a priority right now.

**Comment by salameer** [comment]
@garimakhulbe Do we always have to use encoding with WithPathParameters?

**Comment by garimakhulbe** [comment]
Sorry I missed it earlier don't know how.

No, we don't always encode path parameters. We only do encoding when `x-ms-skip-url-encoding` extension is false which they are not coming encoded. This extension is defined for each parameters so we go param by param encode and create parameter map. Example..
```Go 
p := map[string]interface{}{
        "secret-name": autorest.Encode("path", secretName),
        "abc": abc,
    }
```
Then `WithPathParameters` method joins these values together and create url. 
We can't move `Encode` inside `WithPathParameters()` because we are using it for query parameters as well.

**Comment by salameer** [comment]
Closing based on the last comments
