### ISSUE TITLE
German vs. Germany vs. China vs. Chinese

### ISSUE THREAD

**Issue by boumenot** [Azure/go-autorest#79]
There's a disagreement on naming style for the various clouds.

We have AzureGermanCloud and AzureChinaCloud. It seems more appropriate for German to be Germany.

The Azure XPlat CLI does the same thing.

**Comment by colemickens** [comment]
This goes right back to the discussion we had here: https://github.com/Azure/go-autorest/pull/74. If there was a manifest or even just a documented page with the official names of these things, we could use them as the source of truth.

In the absence of a better source of truth, and given then I'm not picky, it seems best to simply align with azure-xplat-cli.

**Comment by ahmetalpbalkan** [comment]
> There's a disagreement

where? Since we get the data from xplat-cli, it might be better to open an issue against them (instead of fixing it right here). If they fix (which I have doubts, i.e. breaking change), we can fix too.

**Comment by colemickens** [comment]
ref: environment defs in xplat: https://github.com/Azure/azure-xplat-cli/blob/81b16af1b0a70167fbbb7e1cee73afeeefc54b67/lib/util/profile/environment.js#L168

Paul called out the disagreement in the linked `packer` isssue: German is an adjective, while China is a noun. China/Germany or Chinese/German would be more consistent.

**Comment by paulmey** [comment]
@devigned David, how about some justice here? Are y'all planning to fix this linguistic confusion in the xplat cli?

**Comment by devigned** [comment]
@eduardkoller (the new and improved Azure CLI PM) might have an opinion on fixing this. 

Also, I think ARM will have a metadata endpoint for this type of information. We are looking to move to use that in PowerShell.

**Comment by colemickens** [comment]
Maybe we can get a conversation going over on the autorest repo: https://github.com/Azure/autorest/issues/1204 and get everyone involved?

So that we can discuss such things as: when metadata endpoint will be available? Will PS remove all hard coded env information and always/only auto-discover it, or will it just be consume the data during generation time? Etc.

**Comment by devigned** [comment]
Yes, discussing in that thread seems most appropriate.

I think we were leaning toward a known set of uris corresponding to each known cloud meta endpoint and pulling down metadata when needed (not generation time as data could change -- hopefully not often). Perhaps, this would be best added to the client runtimes for each language.

**Comment by vishrutshah** [comment]
@eduardkoller Could you please help us whether this should be discussed here or other thread? Feel free to close this if you find better place for this is in other thread. Thanks!

**Comment by marstr** [comment]
@eduardkoller has moved on to a new team, so he is no longer an appropriate assignee. I'll take over trying to find a better place for this discussion.

**Comment by marstr** [comment]
Please see the above issue for further conversation of this point.
