### ISSUE TITLE
Test tries to access the network

### ISSUE THREAD

**Issue by TheTincho** [Azure/go-autorest#83]
Hi!

While all other tests use mocks correctly to avoid depending on DNS or connectivity to the internet, `TestClientDoSetsUserAgent` is missing such mock, and triggers a DNS query (this is a [bug in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830672)). This small patch fixes that:

```
--- a/autorest/client_test.go
+++ b/autorest/client_test.go
@@ -151,6 +151,8 @@
    ua := "UserAgent"
    c := Client{UserAgent: ua}
    r := mocks.NewRequest()
+   s := mocks.NewSender()
+   c.Sender = s

    c.Do(r)

```

**Comment by ahmetalpbalkan** [comment]
@TheTincho thanks for discovering. Do you mind sending a pull request?

**Comment by TheTincho** [comment]
Sorry, I did not see your reply!

Will do, along with another test that was reported as accessing the network.

**Comment by jhendrixMSFT** [comment]
PR https://github.com/Azure/go-autorest/pull/97 to fix the remaining test that hits the network.

**Comment by jhendrixMSFT** [comment]
The fix has been merged.
