### ISSUE TITLE
Autorest acceptance tests for time not passing

### ISSUE THREAD

**Issue by mcardosos** [Azure/go-autorest#90]
`gulp test:go` in [AutoRest](https://github.com/Azure/autorest) is not passing some time related tests. The most recent go-autorest commit that passes the tests is [8b2eba76ed1c60ffcb68f312d7cff2671516c08e](https://github.com/Azure/go-autorest/tree/8b2eba76ed1c60ffcb68f312d7cff2671516c08e)

**Comment by garimakhulbe** [comment]
Issue is in recent changes in PR #89. We added azure datetime format and check `Z` for format RFC3339. 
However, `1980-01-02T00:11:35+01:00` is valid RFC3339 and it does not have `Z/z`. I think we need to update code in `time` package.

**Comment by mcardosos** [comment]
@jhendrixMSFT fixed this :D
The true origin for this problem is this...
[SDK issue](https://github.com/Azure/azure-sdk-for-go/issues/402)
